"use client";

import { Badge, EmptyState, SurfaceCard } from "@storyboard/ui";
import { BriefcaseBusiness, CalendarDays, ListMusic, Plus, Rocket } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { apiFetch } from "@/lib/api";
import type { ArtistProject, BandEvent, BandMember, Contact, DealOffer, DocumentTemplate, Expense, Invoice, Setlist, Settlement, ShowReadiness, Song, Venue } from "@/lib/types";

type Tab = "events" | "music" | "projects" | "deals";
type Mutate = (path: string, json: unknown, method?: string) => Promise<void>;
const tabs: { id: Tab; label: string; icon: typeof CalendarDays }[] = [{ id: "events", label: "Events", icon: CalendarDays }, { id: "music", label: "Music & setlists", icon: ListMusic }, { id: "projects", label: "Projects", icon: Rocket }, { id: "deals", label: "Deals", icon: BriefcaseBusiness }];
export function OperationsClient({ initialEvents, initialReadiness, initialSongs, initialSetlists, initialProjects, initialDeals, initialInvoices, initialExpenses, initialSettlements, initialTemplates, members, contacts, venues }: { initialEvents: BandEvent[]; initialReadiness: ShowReadiness[]; initialSongs: Song[]; initialSetlists: Setlist[]; initialProjects: ArtistProject[]; initialDeals: DealOffer[]; initialInvoices: Invoice[]; initialExpenses: Expense[]; initialSettlements: Settlement[]; initialTemplates: DocumentTemplate[]; members: BandMember[]; contacts: Contact[]; venues: Venue[] }) {
  const [tab, setTab] = useState<Tab>("events"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const router = useRouter();
  async function create(path: string, json: unknown, method = "POST") { setBusy(true); setError(""); try { await apiFetch(path, { method, json }); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Request failed"); } finally { setBusy(false); } }
  return <div className="space-y-6">{error ? <div role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</div> : null}<div className="flex gap-2 overflow-x-auto border-b border-[var(--border)] pb-3" role="tablist">{tabs.map(({ id, label, icon: Icon }) => <button key={id} role="tab" aria-selected={tab === id} className={tab === id ? "sb-btn-primary shrink-0" : "sb-btn-secondary shrink-0"} onClick={() => setTab(id)}><Icon className="h-4 w-4" />{label}</button>)}</div>{tab === "events" ? <Events events={initialEvents} readiness={initialReadiness} members={members} contacts={contacts} venues={venues} setlists={initialSetlists} busy={busy} create={create} /> : tab === "music" ? <Music songs={initialSongs} setlists={initialSetlists} busy={busy} create={create} /> : tab === "projects" ? <Projects projects={initialProjects} busy={busy} create={create} /> : <Deals deals={initialDeals} invoices={initialInvoices} expenses={initialExpenses} settlements={initialSettlements} templates={initialTemplates} events={initialEvents} projects={initialProjects} members={members} busy={busy} create={create} />}</div>;
}

function Events({ events, readiness, members, contacts, venues, setlists, busy, create }: { events: BandEvent[]; readiness: ShowReadiness[]; members: BandMember[]; contacts: Contact[]; venues: Venue[]; setlists: Setlist[]; busy: boolean; create: Mutate }) {
  const [title, setTitle] = useState("");
  const [type, setType] = useState("gig");
  const [startsAt, setStartsAt] = useState("");
  const byEvent = new Map(readiness.map((item) => [item.eventId, item]));
  const activeMembers = members.filter((member) => member.active);
  return <div className="grid gap-5 lg:grid-cols-[340px_1fr]">
    <SurfaceCard><h2 className="font-semibold">Add an event</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Use events as the hub for people, timing, advance work, and settlement.</p><form className="mt-5 space-y-4" onSubmit={(event) => { event.preventDefault(); void create("/events", { type, title, startsAt: startsAt ? new Date(startsAt).toISOString() : null, status: "draft", currency: "USD" }); setTitle(""); }}><label><span className="sb-label">Event type</span><select className="sb-select mt-1.5" value={type} onChange={(event) => setType(event.target.value)}>{["gig","rehearsal","studio","release","promotion","travel","meeting"].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="sb-label">Title</span><input required className="sb-input mt-1.5" value={title} onChange={(event) => setTitle(event.target.value)} /></label><label><span className="sb-label">Starts</span><input type="datetime-local" className="sb-input mt-1.5" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><button disabled={busy} className="sb-btn-primary"><Plus className="h-4 w-4" /> Add event</button></form></SurfaceCard>
    <SurfaceCard><h2 className="font-semibold">Upcoming and active</h2><div className="mt-4 space-y-4">{events.map((event) => <EventCard key={event.id} event={event} readiness={byEvent.get(event.id) ?? null} members={activeMembers} contacts={contacts} venues={venues} setlists={setlists} busy={busy} create={create} />)}{!events.length ? <EmptyState title="No events yet" description="Add a rehearsal or show, or confirm a booking opportunity." icon={<CalendarDays className="h-6 w-6" />} /> : null}</div></SurfaceCard>
  </div>;
}

function EventCard({ event, readiness, members, contacts, venues, setlists, busy, create }: { event: BandEvent; readiness: ShowReadiness | null; members: BandMember[]; contacts: Contact[]; venues: Venue[]; setlists: Setlist[]; busy: boolean; create: Mutate }) {
  const available = members.filter((member) => event.participants.find((participant) => participant.bandMember.id === member.id)?.response === "available").length;
  return <article className="rounded-xl border border-[var(--border)] p-4">
    <div className="flex items-start justify-between gap-3"><div><p className="font-medium">{event.title}</p><p className="mt-1 text-xs capitalize text-[var(--text-muted)]">{event.type} · {event.startsAt ? new Date(event.startsAt).toLocaleString() : "date not set"}{event.venue?.name ? ` · ${event.venue.name}` : event.locationName ? ` · ${event.locationName}` : ""}</p></div><Badge variant={event.status === "confirmed" ? "success" : "neutral"}>{event.status}</Badge></div>
    <p className="mt-3 text-xs text-[var(--text-muted)]">Availability: {available}/{members.length} active members available</p>
    {readiness ? <div className="mt-4 rounded-lg bg-[var(--surface-subtle)] p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant={readiness.status === "ready" ? "success" : readiness.status === "attention" ? "warning" : "danger"}>{readiness.status.replaceAll("_", " ")}</Badge><span className="text-sm font-semibold">{readiness.score}/100</span><span className="text-xs text-[var(--text-muted)]">{readiness.confidenceLabel} confidence</span></div><p className="mt-2 text-sm">{readiness.headline}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{readiness.categories.map((category) => <div key={category.category} className="rounded-md border border-[var(--border)] px-2 py-1.5"><p className="text-[10px] uppercase tracking-wide text-[var(--text-muted)]">{category.category}</p><p className="text-xs font-medium">{category.score}/{category.maxScore}</p></div>)}</div>{readiness.gaps.length ? <ul className="mt-3 space-y-1.5 text-xs text-[var(--text-muted)]">{readiness.gaps.slice(0, 4).map((gap) => <li key={gap.code}><span className={gap.severity === "high" ? "text-red-300" : "text-[var(--text-secondary)]"}>{gap.title}:</span> {gap.nextAction}</li>)}</ul> : null}{readiness.gaps.some((gap) => gap.code === "advance_missing") && event.startsAt ? <button type="button" className="sb-btn-secondary mt-3" disabled={busy} onClick={() => void create(`/events/${event.id}/generate-advance`, {})}>Generate advance checklist</button> : null}</div> : null}
    {event.type === "gig" ? <a className="sb-btn-secondary mt-4 w-fit" href={`/operations/events/${event.id}`}>Open day-of view</a> : null}
    <details className="mt-4 border-t border-[var(--border)] pt-3"><summary className="cursor-pointer text-sm font-medium text-[var(--accent)]">Manage readiness details</summary><EventDetailsEditor event={event} members={members} contacts={contacts} venues={venues} setlists={setlists} busy={busy} create={create} /></details>
  </article>;
}

function localDateTime(value?: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function isoOrNull(value: string) { return value ? new Date(value).toISOString() : null; }
function dollars(value?: number | null) { return value == null ? "" : (value / 100).toFixed(2); }

function EventDetailsEditor({ event, members, contacts, venues, setlists, busy, create }: { event: BandEvent; members: BandMember[]; contacts: Contact[]; venues: Venue[]; setlists: Setlist[]; busy: boolean; create: Mutate }) {
  const [status, setStatus] = useState(event.status);
  const [venueId, setVenueId] = useState(event.venueId ?? "");
  const [locationName, setLocationName] = useState(event.locationName ?? "");
  const [address, setAddress] = useState(event.address ?? "");
  const [contactId, setContactId] = useState(event.contactId ?? "");
  const [setlistId, setSetlistId] = useState(event.setlistId ?? "");
  const [startsAt, setStartsAt] = useState(localDateTime(event.startsAt));
  const [loadInAt, setLoadInAt] = useState(localDateTime(event.loadInAt));
  const [soundcheckAt, setSoundcheckAt] = useState(localDateTime(event.soundcheckAt));
  const [doorsAt, setDoorsAt] = useState(localDateTime(event.doorsAt));
  const [setAt, setSetAt] = useState(localDateTime(event.setAt));
  const [curfewAt, setCurfewAt] = useState(localDateTime(event.curfewAt));
  const [guarantee, setGuarantee] = useState(dollars(event.guaranteeMinor));
  const [deposit, setDeposit] = useState(dollars(event.depositMinor));
  const [productionNotes, setProductionNotes] = useState(event.productionNotes ?? "");
  const [stagePlotUrl, setStagePlotUrl] = useState(event.stagePlotUrl ?? "");
  const [inputListUrl, setInputListUrl] = useState(event.inputListUrl ?? "");
  const [techRiderUrl, setTechRiderUrl] = useState(event.techRiderUrl ?? "");
  const [attendance, setAttendance] = useState(event.attendance?.toString() ?? "");
  const [grossRevenue, setGrossRevenue] = useState(dollars(event.grossRevenueMinor));
  const [postShowNotes, setPostShowNotes] = useState(event.postShowNotes ?? "");
  const [relationshipOutcome, setRelationshipOutcome] = useState(event.relationshipOutcome ?? "");
  const field = (label: string, value: string, setValue: (value: string) => void) => <label><span className="sb-label">{label}</span><input aria-label={`${label} for ${event.title}`} type="datetime-local" className="sb-input mt-1.5" value={value} onChange={(change) => setValue(change.target.value)} /></label>;
  return <div className="mt-4 space-y-5">
    <div><p className="sb-label">Lineup availability</p>{members.length ? <div className="mt-2 grid gap-2 sm:grid-cols-2">{members.map((member) => { const response = event.participants.find((participant) => participant.bandMember.id === member.id)?.response ?? "unknown"; return <label key={member.id} className="rounded-lg border border-[var(--border)] p-2"><span className="text-sm">{member.name}</span><select aria-label={`Availability for ${member.name} at ${event.title}`} className="sb-select mt-1.5" value={response} disabled={busy} onChange={(change) => void create(`/events/${event.id}/participants`, { bandMemberId: member.id, response: change.target.value })}>{["unknown","available","tentative","unavailable"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label>; })}</div> : <p className="mt-2 text-sm text-[var(--text-muted)]">Add the performing lineup in Manager before collecting availability.</p>}</div>
    <form className="space-y-4" onSubmit={(submit) => { submit.preventDefault(); void create(`/events/${event.id}`, { status, venueId: venueId || null, locationName: locationName || null, address: address || null, contactId: contactId || null, setlistId: setlistId || null, startsAt: isoOrNull(startsAt), loadInAt: isoOrNull(loadInAt), soundcheckAt: isoOrNull(soundcheckAt), doorsAt: isoOrNull(doorsAt), setAt: isoOrNull(setAt), curfewAt: isoOrNull(curfewAt), guaranteeMinor: guarantee === "" ? null : Math.round(Number(guarantee) * 100), depositMinor: deposit === "" ? null : Math.round(Number(deposit) * 100), productionNotes: productionNotes || null, stagePlotUrl: stagePlotUrl || null, inputListUrl: inputListUrl || null, techRiderUrl: techRiderUrl || null, attendance: attendance === "" ? null : Number(attendance), grossRevenueMinor: grossRevenue === "" ? null : Math.round(Number(grossRevenue) * 100), postShowNotes: postShowNotes || null, relationshipOutcome: relationshipOutcome || null }, "PATCH"); }}>
      <div className="grid gap-3 sm:grid-cols-2"><label><span className="sb-label">Status</span><select aria-label={`Status for ${event.title}`} className="sb-select mt-1.5" value={status} onChange={(change) => setStatus(change.target.value)}>{["draft","hold","confirmed","completed","cancelled"].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="sb-label">Venue</span><select aria-label={`Venue for ${event.title}`} className="sb-select mt-1.5" value={venueId} onChange={(change) => setVenueId(change.target.value)}><option value="">No saved venue</option>{venues.map((venue) => <option key={venue.id} value={venue.id}>{venue.name} · {venue.city}</option>)}</select></label><label><span className="sb-label">Location name</span><input aria-label={`Location name for ${event.title}`} className="sb-input mt-1.5" value={locationName} onChange={(change) => setLocationName(change.target.value)} placeholder="Client site, festival stage, or room" /></label><label><span className="sb-label">Address</span><input aria-label={`Address for ${event.title}`} className="sb-input mt-1.5" value={address} onChange={(change) => setAddress(change.target.value)} /></label><label><span className="sb-label">Day-of contact</span><select aria-label={`Day-of contact for ${event.title}`} className="sb-select mt-1.5" value={contactId} onChange={(change) => setContactId(change.target.value)}><option value="">No contact attached</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.fullName}{contact.role ? ` · ${contact.role}` : ""}</option>)}</select></label><label><span className="sb-label">Setlist</span><select aria-label={`Setlist for ${event.title}`} className="sb-select mt-1.5" value={setlistId} onChange={(change) => setSetlistId(change.target.value)}><option value="">No setlist attached</option>{setlists.map((setlist) => <option key={setlist.id} value={setlist.id}>{setlist.name} · {setlist.items.length} items</option>)}</select></label></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{field("Event start", startsAt, setStartsAt)}{field("Load-in", loadInAt, setLoadInAt)}{field("Soundcheck", soundcheckAt, setSoundcheckAt)}{field("Doors", doorsAt, setDoorsAt)}{field("Set time", setAt, setSetAt)}{field("Curfew", curfewAt, setCurfewAt)}</div>
      <div className="grid gap-3 sm:grid-cols-2"><label><span className="sb-label">Guarantee (USD)</span><input aria-label={`Guarantee for ${event.title}`} className="sb-input mt-1.5" type="number" min="0" step="0.01" value={guarantee} onChange={(change) => setGuarantee(change.target.value)} /></label><label><span className="sb-label">Deposit (USD)</span><input aria-label={`Deposit for ${event.title}`} className="sb-input mt-1.5" type="number" min="0" step="0.01" value={deposit} onChange={(change) => setDeposit(change.target.value)} /></label></div>
      <label><span className="sb-label">Production notes</span><textarea aria-label={`Production notes for ${event.title}`} className="sb-input mt-1.5 min-h-24" value={productionNotes} onChange={(change) => setProductionNotes(change.target.value)} placeholder="Backline, power, PA, stage dimensions, changeover, or known constraints" /></label>
      <div className="grid gap-3 sm:grid-cols-3"><label><span className="sb-label">Stage plot URL</span><input aria-label={`Stage plot URL for ${event.title}`} className="sb-input mt-1.5" type="url" value={stagePlotUrl} onChange={(change) => setStagePlotUrl(change.target.value)} placeholder="https://" /></label><label><span className="sb-label">Input list URL</span><input aria-label={`Input list URL for ${event.title}`} className="sb-input mt-1.5" type="url" value={inputListUrl} onChange={(change) => setInputListUrl(change.target.value)} placeholder="https://" /></label><label><span className="sb-label">Tech rider URL</span><input aria-label={`Tech rider URL for ${event.title}`} className="sb-input mt-1.5" type="url" value={techRiderUrl} onChange={(change) => setTechRiderUrl(change.target.value)} placeholder="https://" /></label></div>
      {event.type === "gig" ? <section className="rounded-xl border border-[var(--border)] bg-[var(--surface-0)] p-4"><h3 className="font-medium">After the show</h3><p className="mt-1 text-xs text-[var(--text-muted)]">These facts let the Manager compare results without guessing. Leave an unknown blank.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="sb-label">Attendance</span><input aria-label={`Attendance for ${event.title}`} className="sb-input mt-1.5" type="number" min="0" step="1" value={attendance} onChange={(change) => setAttendance(change.target.value)} /></label><label><span className="sb-label">Gross revenue ({event.currency})</span><input aria-label={`Gross revenue for ${event.title}`} className="sb-input mt-1.5" type="number" min="0" step="0.01" value={grossRevenue} onChange={(change) => setGrossRevenue(change.target.value)} /></label></div><label className="mt-3 block"><span className="sb-label">What happened and what should change?</span><textarea aria-label={`Post-show notes for ${event.title}`} className="sb-input mt-1.5 min-h-24" maxLength={5000} value={postShowNotes} onChange={(change) => setPostShowNotes(change.target.value)} placeholder="Draw, audience response, production issues, merch, promotion, and lessons for next time" /></label><label className="mt-3 block"><span className="sb-label">Buyer / venue relationship outcome</span><textarea aria-label={`Relationship outcome for ${event.title}`} className="sb-input mt-1.5 min-h-20" maxLength={1000} value={relationshipOutcome} onChange={(change) => setRelationshipOutcome(change.target.value)} placeholder="Invited back, requested follow-up, neutral, or relationship issue" /></label></section> : null}
      <button className="sb-btn-primary" disabled={busy}>Save event details</button>
    </form>
  </div>;
}

function Music({ songs, setlists, busy, create }: { songs: Song[]; setlists: Setlist[]; busy: boolean; create: (path: string, json: unknown) => Promise<void> }) { const [title, setTitle] = useState(""); const [duration, setDuration] = useState(""); const [setName, setSetName] = useState(""); return <div className="grid gap-5 lg:grid-cols-2"><SurfaceCard><h2 className="font-semibold">Song library</h2><form className="mt-4 flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); void create("/songs", { title, durationSeconds: duration ? Number(duration) * 60 : null, active: true }); setTitle(""); }}><input required className="sb-input" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Song title" /><input className="sb-input w-28" type="number" min="1" value={duration} onChange={(event) => setDuration(event.target.value)} placeholder="Minutes" /><button disabled={busy} className="sb-btn-primary">Add</button></form><div className="mt-5 divide-y divide-[var(--border)]">{songs.map((song) => <div key={song.id} className="flex items-center justify-between py-3"><p className="font-medium">{song.title}</p><p className="text-xs text-[var(--text-muted)]">{song.durationSeconds ? `${Math.floor(song.durationSeconds / 60)}:${String(song.durationSeconds % 60).padStart(2,"0")}` : "duration unknown"}</p></div>)}</div></SurfaceCard><SurfaceCard><h2 className="font-semibold">Setlists</h2><form className="mt-4 flex gap-3" onSubmit={(event) => { event.preventDefault(); void create("/setlists", { name: setName, status: "draft", items: [] }); setSetName(""); }}><input required className="sb-input" value={setName} onChange={(event) => setSetName(event.target.value)} placeholder="Setlist name" /><button disabled={busy} className="sb-btn-primary">Create</button></form><div className="mt-5 space-y-3">{setlists.map((setlist) => <div key={setlist.id} className="rounded-lg border border-[var(--border)] p-3"><div className="flex justify-between"><p className="font-medium">{setlist.name}</p><Badge variant="neutral">{setlist.status}</Badge></div><p className="mt-1 text-xs text-[var(--text-muted)]">{setlist.items.length} item{setlist.items.length === 1 ? "" : "s"}</p></div>)}</div></SurfaceCard></div>; }

function Projects({ projects, busy, create }: { projects: ArtistProject[]; busy: boolean; create: (path: string, json: unknown) => Promise<void> }) {
  const [name, setName] = useState(""); const [type, setType] = useState("release"); const [dueAt, setDueAt] = useState("");
  return <div className="grid gap-5 lg:grid-cols-[340px_1fr]"><SurfaceCard><h2 className="font-semibold">Start a project</h2><p className="mt-1 text-sm text-[var(--text-muted)]">A real target date lets StoryBoard build the milestone sequence backward.</p><form className="mt-4 space-y-4" onSubmit={(event) => { event.preventDefault(); void create("/projects", { type, name, status: "active", dueAt: dueAt ? new Date(`${dueAt}T12:00:00`).toISOString() : null, currency: "USD", successMetrics: [], assets: [] }); setName(""); }}><select aria-label="Project type" className="sb-select" value={type} onChange={(event) => setType(event.target.value)}>{["release","content_campaign","tour","business"].map((value) => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</select><input required className="sb-input" value={name} onChange={(event) => setName(event.target.value)} placeholder="Project name" /><input aria-label="Project due date" className="sb-input" type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /><button disabled={busy} className="sb-btn-primary">Create project</button></form></SurfaceCard><SurfaceCard><h2 className="font-semibold">Active projects</h2><div className="mt-4 space-y-3">{projects.map((project) => <div key={project.id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{project.name}</p><p className="mt-1 text-xs capitalize text-[var(--text-muted)]">{project.type.replace("_", " ")}{project.dueAt ? ` · due ${new Date(project.dueAt).toLocaleDateString()}` : " · date not set"}</p></div><Badge variant={project.readiness?.status === "on_track" || project.readiness?.status === "complete" ? "success" : project.readiness?.status === "closed" ? "neutral" : project.readiness?.status === "blocked" || project.readiness?.status === "off_track" ? "danger" : "warning"}>{project.readiness ? `${project.readiness.score}/100` : project.status}</Badge></div>{project.readiness ? <><p className="mt-3 text-sm text-[var(--text-secondary)]">{project.readiness.headline}</p><p className="mt-1 text-xs text-[var(--text-muted)]">Next: {project.readiness.nextAction}</p></> : null}<a className="sb-btn-secondary mt-3 w-fit" href={`/operations/projects/${project.id}`}>Open project</a></div>)}{!projects.length ? <EmptyState title="No projects" description="Use a project for a release, tour, campaign, or business initiative." icon={<Rocket className="h-6 w-6" />} /> : null}</div></SurfaceCard></div>;
}

function Deals({ deals, invoices, expenses, settlements, templates, events, projects, members, busy, create }: { deals: DealOffer[]; invoices: Invoice[]; expenses: Expense[]; settlements: Settlement[]; templates: DocumentTemplate[]; events: BandEvent[]; projects: ArtistProject[]; members: BandMember[]; busy: boolean; create: Mutate }) {
  const [title, setTitle] = useState(""); const [buyer, setBuyer] = useState(""); const [email, setEmail] = useState(""); const [amount, setAmount] = useState("");
  const [invoiceDeal, setInvoiceDeal] = useState(""); const [invoiceNumber, setInvoiceNumber] = useState(""); const [invoiceRecipient, setInvoiceRecipient] = useState(""); const [invoiceAmount, setInvoiceAmount] = useState("");
  const [expenseScope, setExpenseScope] = useState(""); const [expenseDescription, setExpenseDescription] = useState(""); const [expenseAmount, setExpenseAmount] = useState("");
  const [settlementEvent, setSettlementEvent] = useState(""); const [settlementGross, setSettlementGross] = useState(""); const [templateName, setTemplateName] = useState("");
  const activeTemplate = templates.find((template) => template.kind === "agreement" && template.active);
  const equalSplits = () => members.map((member, index) => { const base = Math.floor(10000 / members.length); return { bandMemberId: member.id, basisPoints: index === members.length - 1 ? 10000 - base * (members.length - 1) : base }; });
  return <div className="space-y-5">
    <div className="grid gap-5 lg:grid-cols-[340px_1fr]"><SurfaceCard><h2 className="font-semibold">Record an offer</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Amounts use cents internally. Documents require an owner-reviewed template.</p><form className="mt-4 space-y-4" onSubmit={(event) => { event.preventDefault(); void create("/deals", { title, buyerName: buyer || null, buyerEmail: email || null, offerAmountMinor: amount ? Math.round(Number(amount) * 100) : null, currency: "USD", status: "draft" }); setTitle(""); }}><input required className="sb-input" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Show or deal" /><input className="sb-input" value={buyer} onChange={(event) => setBuyer(event.target.value)} placeholder="Buyer name" /><input className="sb-input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Buyer email" /><input className="sb-input" type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Offer amount (USD)" /><button disabled={busy} className="sb-btn-primary">Record offer</button></form></SurfaceCard><SurfaceCard><h2 className="font-semibold">Deal pipeline</h2><div className="mt-4 space-y-3">{deals.map((deal) => <div key={deal.id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-medium">{deal.title}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{deal.buyerName ?? "Buyer unknown"} · {deal.offerAmountMinor == null ? "amount TBD" : `${deal.currency} ${(deal.offerAmountMinor / 100).toFixed(2)}`} · {deal.agreements.length ? `agreement v${deal.agreements[0]?.version}` : "no agreement"}</p></div><Badge variant={deal.status === "accepted" ? "success" : "neutral"}>{deal.status}</Badge></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" className="sb-btn-secondary" disabled={busy || !activeTemplate} onClick={() => void create(`/deals/${deal.id}/generate-document`, {})}>Generate agreement PDF</button>{deal.agreements.length && deal.buyerEmail ? <button type="button" className="sb-btn-secondary" disabled={busy} onClick={() => void create(`/deals/${deal.id}/prepare-delivery`, {})}>Prepare delivery approval</button> : null}</div></div>)}{!deals.length ? <EmptyState title="No offers yet" description="Record quotes, guarantees, and event buyer terms here." icon={<BriefcaseBusiness className="h-6 w-6" />} /> : null}</div></SurfaceCard></div>
    <div className="grid gap-5 xl:grid-cols-3"><SurfaceCard><h2 className="font-semibold">Agreement template</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Owner activation required. Template only—not legal advice.</p><form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); void create("/document-templates", { kind: "agreement", name: templateName, bodyTemplate: "Agreement between {{artistName}} and {{buyerName}} for {{performanceDate}}. Fee: {{currency}} {{amount}}.\n\nTerms: {{terms}}\n\nCancellation: {{cancellationTerms}}" }); setTemplateName(""); }}><input required className="sb-input" value={templateName} onChange={(event) => setTemplateName(event.target.value)} placeholder="Template name" /><button disabled={busy} className="sb-btn-secondary">Create reviewed version</button></form><div className="mt-3 space-y-2">{templates.filter((template) => template.kind === "agreement").map((template) => <div key={template.id} className="flex items-center justify-between gap-2 rounded-lg border border-[var(--border)] p-2 text-sm"><span>{template.name} v{template.version}</span>{template.active ? <Badge variant="success">active</Badge> : <button className="sb-btn-ghost" onClick={() => void create(`/document-templates/${template.id}/activate`, {}, "PUT")}>Activate</button>}</div>)}</div></SurfaceCard>
      <SurfaceCard><h2 className="font-semibold">Issue an invoice</h2><form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); const deal = deals.find((row) => row.id === invoiceDeal); void create("/invoices", { dealOfferId: invoiceDeal, eventId: null, number: invoiceNumber, recipientName: invoiceRecipient, recipientEmail: deal?.buyerEmail ?? null, currency: "USD", subtotalMinor: Math.round(Number(invoiceAmount) * 100), taxMinor: 0 }); setInvoiceNumber(""); }}><select aria-label="Invoice deal" required className="sb-select" value={invoiceDeal} onChange={(event) => setInvoiceDeal(event.target.value)}><option value="">Select deal</option>{deals.map((deal) => <option key={deal.id} value={deal.id}>{deal.title}</option>)}</select><input required className="sb-input" value={invoiceNumber} onChange={(event) => setInvoiceNumber(event.target.value)} placeholder="Invoice number" /><input required className="sb-input" value={invoiceRecipient} onChange={(event) => setInvoiceRecipient(event.target.value)} placeholder="Recipient" /><input required className="sb-input" min="0" step="0.01" type="number" value={invoiceAmount} onChange={(event) => setInvoiceAmount(event.target.value)} placeholder="Amount (USD)" /><button disabled={busy} className="sb-btn-primary">Create invoice</button></form></SurfaceCard>
      <SurfaceCard><h2 className="font-semibold">Record an expense</h2><form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); const [kind, id] = expenseScope.split(":"); void create("/expenses", { eventId: kind === "event" ? id : null, projectId: kind === "project" ? id : null, category: "other", description: expenseDescription, amountMinor: Math.round(Number(expenseAmount) * 100), currency: "USD", incurredAt: new Date().toISOString() }); setExpenseDescription(""); }}><select aria-label="Expense event or project" required className="sb-select" value={expenseScope} onChange={(event) => setExpenseScope(event.target.value)}><option value="">Event or project</option>{events.map((row) => <option key={row.id} value={`event:${row.id}`}>{row.title}</option>)}{projects.map((row) => <option key={row.id} value={`project:${row.id}`}>{row.name}</option>)}</select><input required className="sb-input" value={expenseDescription} onChange={(event) => setExpenseDescription(event.target.value)} placeholder="Expense description" /><input required className="sb-input" min="0.01" step="0.01" type="number" value={expenseAmount} onChange={(event) => setExpenseAmount(event.target.value)} placeholder="Amount (USD)" /><button disabled={busy} className="sb-btn-secondary">Record expense</button></form></SurfaceCard></div>
    <div className="grid gap-5 lg:grid-cols-2"><SurfaceCard><h2 className="font-semibold">Invoices and payments</h2><div className="mt-4 space-y-3">{invoices.map((invoice) => <InvoiceRow key={invoice.id} invoice={invoice} busy={busy} create={create} />)}{!invoices.length ? <p className="text-sm text-[var(--text-muted)]">No invoices yet.</p> : null}</div></SurfaceCard><SurfaceCard><h2 className="font-semibold">Settle a completed show</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Current event expenses are deducted; net is split equally across the active lineup.</p><form className="mt-4 flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); void create("/settlements", { eventId: settlementEvent, currency: "USD", grossMinor: Math.round(Number(settlementGross) * 100), splits: equalSplits() }); }}><select aria-label="Settlement event" required className="sb-select" value={settlementEvent} onChange={(event) => setSettlementEvent(event.target.value)}><option value="">Select event</option>{events.filter((event) => event.type === "gig").map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select><input required className="sb-input" min="0" step="0.01" type="number" value={settlementGross} onChange={(event) => setSettlementGross(event.target.value)} placeholder="Gross USD" /><button disabled={busy || members.length === 0} className="sb-btn-primary">Calculate</button></form><div className="mt-4 space-y-2">{settlements.map((settlement) => <div key={settlement.id} className="flex flex-col gap-3 rounded-lg border border-[var(--border)] p-3 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-medium">{settlement.event.title}</p><p className="text-xs text-[var(--text-muted)]">Net {settlement.currency} {(settlement.netMinor / 100).toFixed(2)}</p></div>{settlement.status === "draft" ? <button className="sb-btn-secondary" disabled={busy} onClick={() => void create(`/settlements/${settlement.id}/finalize`, {})}>Finalize PDF</button> : <Badge variant="success">finalized</Badge>}</div>)}</div></SurfaceCard></div>
    {expenses.length ? <SurfaceCard><h2 className="font-semibold">Recent expenses</h2><div className="mt-3 divide-y divide-[var(--border)]">{expenses.slice(0, 10).map((expense) => <div key={expense.id} className="flex justify-between gap-4 py-3 text-sm"><span>{expense.description}<span className="ml-2 text-[var(--text-muted)]">{expense.event?.title ?? expense.project?.name}</span></span><span>{expense.currency} {(expense.amountMinor / 100).toFixed(2)}</span></div>)}</div></SurfaceCard> : null}
  </div>;
}

function InvoiceRow({ invoice, busy, create }: { invoice: Invoice; busy: boolean; create: Mutate }) { const [amount, setAmount] = useState(""); const balance = invoice.totalMinor - invoice.paidMinor; return <div className="rounded-lg border border-[var(--border)] p-3"><div className="flex items-center justify-between"><div><p className="font-medium">{invoice.number} · {invoice.recipientName}</p><p className="text-xs text-[var(--text-muted)]">Balance {invoice.currency} {(balance / 100).toFixed(2)}</p></div><Badge variant={balance === 0 ? "success" : "neutral"}>{invoice.status}</Badge></div>{balance > 0 ? <form className="mt-3 flex gap-2" onSubmit={(event) => { event.preventDefault(); void create(`/invoices/${invoice.id}/record-payment`, { idempotencyKey: `manual-${invoice.id}-${Date.now()}`, amountMinor: Math.round(Number(amount) * 100), currency: invoice.currency, method: "manual", receivedAt: new Date().toISOString() }); setAmount(""); }}><input required className="sb-input" type="number" min="0.01" max={(balance / 100).toFixed(2)} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Payment" /><button disabled={busy} className="sb-btn-secondary">Record</button></form> : null}</div>; }
