import { PageHeader } from "@storyboard/ui";
import { serverApiFetch } from "@/lib/api-server";
import type { ArtistProject, BandEvent, BandMember, DealOffer, DocumentTemplate, Expense, Invoice, Setlist, Settlement, ShowReadiness, Song } from "@/lib/types";
import { OperationsClient } from "./operations-client";

export default async function OperationsPage() {
  let events: BandEvent[] = []; let readiness: ShowReadiness[] = []; let songs: Song[] = []; let setlists: Setlist[] = []; let projects: ArtistProject[] = []; let deals: DealOffer[] = []; let invoices: Invoice[] = []; let expenses: Expense[] = []; let settlements: Settlement[] = []; let templates: DocumentTemplate[] = []; let members: BandMember[] = [];
  try { [events, readiness, songs, setlists, projects, deals, invoices, expenses, settlements, templates, members] = await Promise.all([serverApiFetch<BandEvent[]>("/events", { cache: "no-store" }), serverApiFetch<ShowReadiness[]>("/events/readiness?days=120", { cache: "no-store" }), serverApiFetch<Song[]>("/songs", { cache: "no-store" }), serverApiFetch<Setlist[]>("/setlists", { cache: "no-store" }), serverApiFetch<ArtistProject[]>("/projects", { cache: "no-store" }), serverApiFetch<DealOffer[]>("/deals", { cache: "no-store" }), serverApiFetch<Invoice[]>("/invoices", { cache: "no-store" }), serverApiFetch<Expense[]>("/expenses", { cache: "no-store" }), serverApiFetch<Settlement[]>("/settlements", { cache: "no-store" }), serverApiFetch<DocumentTemplate[]>("/document-templates", { cache: "no-store" }), serverApiFetch<BandMember[]>("/manager/members", { cache: "no-store" })]); } catch { /* empty workspace */ }
  return <div className="space-y-8"><PageHeader title="Band operations" description="Shows, rehearsals, music, projects, and deal readiness in one working layer." /><OperationsClient initialEvents={events} initialReadiness={readiness} initialSongs={songs} initialSetlists={setlists} initialProjects={projects} initialDeals={deals} initialInvoices={invoices} initialExpenses={expenses} initialSettlements={settlements} initialTemplates={templates} members={members} /></div>;
}
