"use client";

import { Badge, SurfaceCard } from "@storyboard/ui";
import { ArrowLeft, Check, Clock3, Mail, MapPin, Pencil, Phone, Plus, RefreshCw, Save, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { apiFetch } from "@/lib/api";
import type { EventDayOfResponse } from "@/lib/types";

function money(value: number | null | undefined, currency: string) { return value == null ? "Not recorded" : `${currency} ${(value / 100).toFixed(2)}`; }
function time(value: string) { return new Date(value).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); }
function relative(minutes: number) { if (minutes === 0) return "now"; if (minutes > 0) return minutes < 60 ? `in ${minutes}m` : `in ${Math.floor(minutes / 60)}h ${minutes % 60}m`; const elapsed = Math.abs(minutes); return elapsed < 60 ? `${elapsed}m ago` : `${Math.floor(elapsed / 60)}h ${elapsed % 60}m ago`; }
function localDateTime(value?: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export function DayOfClient({ initialData }: { initialData: EventDayOfResponse }) {
  const { event, activeMembers, readiness, dayOf } = initialData;
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState("");
  const router = useRouter();
  async function mutate(key: string, path: string, json?: unknown, method = "POST") {
    setBusy(key); setError("");
    try { await apiFetch(path, { method, ...(json === undefined ? {} : { json }) }); router.refresh(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "The update failed"); }
    finally { setBusy(null); }
  }
  const setlistSeconds = event.setlist?.items.reduce((sum, item) => sum + (item.song?.durationSeconds ?? 0), 0) ?? 0;
  const location = event.address ?? event.venue?.addressLine ?? event.locationName ?? event.venue?.name;
  return <div className="space-y-5 pb-16">
    <div className="flex flex-wrap items-center justify-between gap-3"><a href="/operations" className="sb-btn-ghost"><ArrowLeft className="h-4 w-4" /> Band operations</a><button type="button" className="sb-btn-secondary" onClick={() => router.refresh()}><RefreshCw className="h-4 w-4" /> Refresh now</button></div>
    {error ? <p role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</p> : null}
    <SurfaceCard className="border-[var(--accent)]/30"><div className="flex flex-wrap items-center gap-2"><Badge variant={readiness.status === "ready" ? "success" : readiness.status === "attention" ? "warning" : "danger"}>{readiness.status.replaceAll("_", " ")}</Badge><span className="text-lg font-semibold">{readiness.score}/100</span><span className="text-xs text-[var(--text-muted)]">{readiness.confidenceLabel} confidence · updated {new Date(dayOf.observedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</span></div><h2 className="mt-4 text-xl font-semibold">{dayOf.headline}</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{dayOf.nextAction}</p>{readiness.gaps[0] ? <p className="mt-3 text-xs text-[var(--text-muted)]">Highest gap: {readiness.gaps[0].title} — {readiness.gaps[0].detail}</p> : null}</SurfaceCard>

    <div className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
      <SurfaceCard><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-[var(--accent)]" /><h2 className="font-semibold">Run of show</h2></div><div className="mt-4 space-y-2">{dayOf.timeline.map((item) => <div key={item.id} className={`flex gap-3 rounded-lg border p-3 ${item.state === "next" ? "border-[var(--accent)] bg-[var(--accent)]/10" : "border-[var(--border)]"}`}><div className="w-20 shrink-0"><p className="font-semibold">{time(item.at)}</p><p className="text-[11px] text-[var(--text-muted)]">{relative(item.minutesUntil)}</p></div><div><div className="flex items-center gap-2"><p className={item.state === "passed" ? "text-[var(--text-muted)] line-through" : "font-medium"}>{item.label}</p>{item.state === "next" ? <Badge variant="accent">next</Badge> : null}</div>{item.location ? <p className="mt-1 text-xs text-[var(--text-muted)]">{item.location}</p> : null}{item.notes ? <p className="mt-1 text-xs text-[var(--text-secondary)]">{item.notes}</p> : null}</div></div>)}{!dayOf.timeline.length ? <p className="rounded-lg border border-dashed border-[var(--border)] p-4 text-sm text-[var(--text-muted)]">No load-in, soundcheck, doors, set, curfew, or custom schedule items are recorded.</p> : null}</div><ScheduleEditor eventId={event.id} schedule={event.schedule ?? []} busy={busy !== null} onMutate={mutate} /></SurfaceCard>

      <div className="space-y-5"><SurfaceCard><h2 className="font-semibold">Place and day-of contact</h2><div className="mt-4 space-y-3 text-sm">{event.venue?.name || event.locationName ? <div><p className="font-medium">{event.venue?.name ?? event.locationName}</p>{event.address || event.venue?.addressLine ? <p className="text-[var(--text-muted)]">{event.address ?? event.venue?.addressLine}</p> : null}</div> : <p className="text-[var(--text-muted)]">No location is recorded.</p>}{location ? <a className="sb-btn-secondary w-fit" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`}><MapPin className="h-4 w-4" /> Open map</a> : null}{event.contact ? <div className="border-t border-[var(--border)] pt-3"><p className="font-medium">{event.contact.fullName}</p><p className="text-xs text-[var(--text-muted)]">{event.contact.role ?? event.contact.contactKind}</p><div className="mt-2 flex flex-wrap gap-2">{event.contact.phone ? <a className="sb-btn-secondary" href={`tel:${event.contact.phone}`}><Phone className="h-4 w-4" /> Call</a> : null}{event.contact.email ? <a className="sb-btn-secondary" href={`mailto:${event.contact.email}`}><Mail className="h-4 w-4" /> Email</a> : null}</div></div> : <p className="border-t border-[var(--border)] pt-3 text-[var(--text-muted)]">No day-of contact is attached.</p>}</div></SurfaceCard>
      <SurfaceCard><h2 className="font-semibold">Money checkpoint</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-[var(--text-muted)]">Expected fee</dt><dd className="font-medium">{money(dayOf.expectedFeeMinor, dayOf.currency)}</dd></div><div><dt className="text-[var(--text-muted)]">Expected deposit</dt><dd className="font-medium">{money(dayOf.expectedDepositMinor, dayOf.currency)}</dd></div><div><dt className="text-[var(--text-muted)]">Recorded paid</dt><dd className="font-medium">{money(dayOf.recordedPaidMinor, dayOf.currency)}</dd></div><div><dt className="text-[var(--text-muted)]">Invoice balance</dt><dd className="font-medium">{money(dayOf.openInvoiceBalanceMinor, dayOf.currency)}</dd></div></dl>{dayOf.depositRemainingMinor > 0 ? <p className="mt-3 text-xs text-amber-200">Deposit still unrecorded: {money(dayOf.depositRemainingMinor, dayOf.currency)}</p> : null}</SurfaceCard></div>
    </div>

    <div className="grid gap-5 lg:grid-cols-2"><SurfaceCard><h2 className="font-semibold">Lineup and assignments</h2><div className="mt-4 space-y-2">{activeMembers.map((member) => { const participant = event.participants.find((item) => item.bandMember.id === member.id); const response = participant?.response ?? "unknown"; const assignment = participant?.assignment ?? (member.instruments?.join(", ") || "No assignment recorded"); return <div key={member.id} className="rounded-lg border border-[var(--border)] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{member.name}</p><p className="text-xs text-[var(--text-muted)]">{assignment}</p></div><select aria-label={`Day-of availability for ${member.name}`} className="sb-select w-auto" value={response} disabled={busy !== null} onChange={(change) => void mutate(`member-${member.id}`, `/events/${event.id}/participants`, { bandMemberId: member.id, response: change.target.value, assignment: participant?.assignment ?? null, notes: participant?.notes ?? null })}>{["unknown", "available", "tentative", "unavailable"].map((value) => <option key={value}>{value}</option>)}</select></div></div>; })}</div></SurfaceCard>
      <SurfaceCard><h2 className="font-semibold">Advance work</h2><p className="mt-1 text-xs text-[var(--text-muted)]">{dayOf.openTaskCount} open · {dayOf.overdueTaskCount} overdue</p><div className="mt-4 space-y-2">{event.tasks?.map((task) => <div key={task.id} className="flex items-center gap-3 rounded-lg border border-[var(--border)] p-3"><div className="min-w-0 flex-1"><p className={task.status === "done" ? "text-sm text-[var(--text-muted)] line-through" : "text-sm font-medium"}>{task.title}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{task.bandMember?.name ?? task.ownerLabel ?? "Unassigned"}{task.dueAt ? ` · due ${new Date(task.dueAt).toLocaleDateString()}` : ""}</p></div>{task.status === "done" ? <Badge variant="success">done</Badge> : <button type="button" className="sb-btn-secondary shrink-0" disabled={busy !== null} onClick={() => void mutate(`task-${task.id}`, `/tasks/${task.id}`, { status: "done" }, "PATCH")}><Check className="h-4 w-4" /> Done</button>}</div>)}{!event.tasks?.length ? <p className="text-sm text-[var(--text-muted)]">No event tasks are recorded.</p> : null}</div></SurfaceCard></div>

    <div className="grid gap-5 lg:grid-cols-2"><SurfaceCard><h2 className="font-semibold">Setlist</h2>{event.setlist ? <><div className="mt-2 flex items-center justify-between"><p className="text-sm text-[var(--text-muted)]">{event.setlist.name}</p><p className="text-xs text-[var(--text-muted)]">{setlistSeconds ? `${Math.floor(setlistSeconds / 60)} min` : "duration unknown"}</p></div><ol className="mt-4 space-y-2">{event.setlist.items.map((item, index) => <li key={item.id} className="flex gap-3 rounded-lg border border-[var(--border)] p-3"><span className="text-xs text-[var(--text-muted)]">{index + 1}</span><div><p className="text-sm font-medium">{item.song?.title ?? item.label ?? item.itemType}</p>{item.transitionNotes ? <p className="mt-1 text-xs text-[var(--text-muted)]">{item.transitionNotes}</p> : null}</div></li>)}</ol></> : <p className="mt-3 text-sm text-[var(--text-muted)]">No setlist is attached.</p>}</SurfaceCard>
      <SurfaceCard><h2 className="font-semibold">Production and logistics</h2><div className="mt-4 space-y-3 text-sm">{event.productionNotes ? <p>{event.productionNotes}</p> : <p className="text-[var(--text-muted)]">No production notes are recorded.</p>}{event.parkingNotes ? <p><span className="font-medium">Parking:</span> {event.parkingNotes}</p> : null}{event.hospitalityNotes ? <p><span className="font-medium">Hospitality:</span> {event.hospitalityNotes}</p> : null}{event.travelNotes ? <p><span className="font-medium">Travel:</span> {event.travelNotes}</p> : null}<div className="flex flex-wrap gap-2">{[["Stage plot", event.stagePlotUrl], ["Input list", event.inputListUrl], ["Tech rider", event.techRiderUrl], ["Hospitality rider", event.hospitalityRiderUrl], ["Drive folder", event.driveFolderUrl]].filter((item): item is [string, string] => Boolean(item[1])).map(([label, url]) => <a key={label} className="sb-btn-secondary" target="_blank" rel="noreferrer" href={url}>{label}</a>)}</div></div></SurfaceCard></div>
  </div>;
}

type ScheduleItem = NonNullable<EventDayOfResponse["event"]["schedule"]>[number];

function ScheduleEditor({ eventId, schedule, busy, onMutate }: { eventId: string; schedule: ScheduleItem[]; busy: boolean; onMutate: (key: string, path: string, json?: unknown, method?: string) => Promise<void> }) {
  const [creating, setCreating] = useState(false);
  const [title, setTitle] = useState("");
  const [startsAt, setStartsAt] = useState("");
  const [endsAt, setEndsAt] = useState("");
  const [location, setLocation] = useState("");
  const [notes, setNotes] = useState("");
  async function create() {
    await onMutate("schedule-new", `/events/${eventId}/schedule`, { title, startsAt: new Date(startsAt).toISOString(), endsAt: endsAt ? new Date(endsAt).toISOString() : null, location: location.trim() || null, notes: notes.trim() || null, sortOrder: schedule.length * 10 });
    setTitle(""); setStartsAt(""); setEndsAt(""); setLocation(""); setNotes(""); setCreating(false);
  }
  return <div className="mt-5 border-t border-[var(--border)] pt-4" data-testid="run-of-show-editor"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium">Custom checkpoints</p><p className="mt-1 text-xs text-[var(--text-muted)]">Add travel calls, meals, support slots, changeovers, meet-and-greets, or anything else the band needs. Use the main event editor for load-in, soundcheck, doors, set, and curfew.</p></div><button type="button" className="sb-btn-secondary" disabled={busy} onClick={() => setCreating((value) => !value)}>{creating ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />} {creating ? "Cancel" : "Add checkpoint"}</button></div>
    {creating ? <div className="mt-4 rounded-lg border border-[var(--accent)]/30 bg-[var(--accent)]/5 p-3"><div className="grid gap-3 sm:grid-cols-2"><label><span className="sb-label">Checkpoint title</span><input className="sb-input mt-1" value={title} maxLength={160} onChange={(event) => setTitle(event.target.value)} /></label><label><span className="sb-label">Location (optional)</span><input className="sb-input mt-1" value={location} maxLength={240} onChange={(event) => setLocation(event.target.value)} /></label><label><span className="sb-label">Checkpoint starts</span><input required type="datetime-local" className="sb-input mt-1" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><label><span className="sb-label">Checkpoint ends (optional)</span><input type="datetime-local" className="sb-input mt-1" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></label><label className="sm:col-span-2"><span className="sb-label">Checkpoint notes (optional)</span><textarea className="sb-input mt-1 min-h-20" value={notes} maxLength={2000} onChange={(event) => setNotes(event.target.value)} /></label></div><button type="button" className="sb-btn-primary mt-3" disabled={busy || !title.trim() || !startsAt} onClick={() => void create()}><Save className="h-4 w-4" /> Save checkpoint</button></div> : null}
    <div className="mt-4 space-y-2">{schedule.map((item) => <ScheduleEditorRow key={item.id} eventId={eventId} item={item} busy={busy} onMutate={onMutate} />)}{!schedule.length ? <p className="text-xs text-[var(--text-muted)]">No custom checkpoints yet.</p> : null}</div>
  </div>;
}

function ScheduleEditorRow({ eventId, item, busy, onMutate }: { eventId: string; item: ScheduleItem; busy: boolean; onMutate: (key: string, path: string, json?: unknown, method?: string) => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const [title, setTitle] = useState(item.title);
  const [startsAt, setStartsAt] = useState(localDateTime(item.startsAt));
  const [endsAt, setEndsAt] = useState(localDateTime(item.endsAt));
  const [location, setLocation] = useState(item.location ?? "");
  const [notes, setNotes] = useState(item.notes ?? "");
  const [sortOrder, setSortOrder] = useState(item.sortOrder);
  async function save() {
    await onMutate(`schedule-${item.id}`, `/events/${eventId}/schedule/${item.id}`, { title, startsAt: new Date(startsAt).toISOString(), endsAt: endsAt ? new Date(endsAt).toISOString() : null, location: location.trim() || null, notes: notes.trim() || null, sortOrder }, "PATCH");
    setEditing(false);
  }
  if (!editing) return <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-[var(--border)] p-3"><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{new Date(item.startsAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}{item.endsAt ? ` – ${new Date(item.endsAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}` : ""}{item.location ? ` · ${item.location}` : ""}</p></div><button type="button" className="sb-btn-ghost" disabled={busy} onClick={() => setEditing(true)}><Pencil className="h-4 w-4" /> Edit {item.title}</button></div>;
  return <div className="rounded-lg border border-[var(--accent)]/30 p-3"><div className="grid gap-3 sm:grid-cols-2"><label><span className="sb-label">Title for {item.title}</span><input className="sb-input mt-1" value={title} maxLength={160} onChange={(event) => setTitle(event.target.value)} /></label><label><span className="sb-label">Location for {item.title}</span><input className="sb-input mt-1" value={location} maxLength={240} onChange={(event) => setLocation(event.target.value)} /></label><label><span className="sb-label">Starts for {item.title}</span><input type="datetime-local" className="sb-input mt-1" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><label><span className="sb-label">Ends for {item.title}</span><input type="datetime-local" className="sb-input mt-1" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></label><label><span className="sb-label">Order for {item.title}</span><input type="number" min={0} max={999} className="sb-input mt-1" value={sortOrder} onChange={(event) => setSortOrder(Number(event.target.value))} /></label><label className="sm:col-span-2"><span className="sb-label">Notes for {item.title}</span><textarea className="sb-input mt-1 min-h-20" value={notes} maxLength={2000} onChange={(event) => setNotes(event.target.value)} /></label></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" className="sb-btn-primary" disabled={busy || !title.trim() || !startsAt} onClick={() => void save()}><Save className="h-4 w-4" /> Save changes</button><button type="button" className="sb-btn-ghost" disabled={busy} onClick={() => setEditing(false)}><X className="h-4 w-4" /> Cancel</button><button type="button" className="sb-btn-ghost text-red-300" disabled={busy} onClick={() => void onMutate(`schedule-${item.id}`, `/events/${eventId}/schedule/${item.id}`, undefined, "DELETE")}><Trash2 className="h-4 w-4" /> Remove checkpoint</button></div></div>;
}
