import { expect, test, type Page } from "@playwright/test";

async function signInForBrowserTest(page: Page) {
  await page.goto("http://127.0.0.1:4000/auth/dev/login");
  await expect(page.getByText("Your operational home base")).toBeVisible();
  await expect.poll(async () => (await page.context().cookies()).some((cookie) => cookie.name === "sb_session"), { message: "Dev login must establish the browser session cookie" }).toBe(true);
}

test("manual prospect can gain a buyer and enter an approval-ready campaign", async ({ page }) => {
  const suffix = Date.now().toString(36);
  const prospectName = `E2E Buyer Lead ${suffix}`;

  // The runner resets only the explicit test database, then seeds this owner
  // workspace so first-use flows remain deterministic across iterations.
  await signInForBrowserTest(page);

  await page.goto("/prospects");
  await page.getByLabel("Home city").fill("Austin");
  await page.getByLabel("Genres (comma separated)").fill("indie rock");
  await page.getByLabel("Capacity minimum").fill("100");
  await page.getByLabel("Capacity maximum").fill("500");
  await page.getByLabel("Short booking pitch").fill("A sharp, audience-ready live set.");
  await page.getByRole("button", { name: "Save profile" }).click();
  await expect(page.getByText("Ready to book")).toBeVisible();

  const manualLead = page.getByText("Add a manual lead").locator("..");
  await manualLead.getByLabel("Name").fill(prospectName);
  await manualLead.getByLabel("City", { exact: true }).fill("Austin");
  await manualLead.getByRole("button", { name: "Save lead" }).click();
  const status = page.getByLabel(`Status for ${prospectName}`);
  await status.selectOption("qualified");
  const card = status.locator("..");
  await card.getByRole("button", { name: "Add/link buyer" }).click();
  await card.getByRole("button", { name: "New buyer/promoter" }).click();
  await card.getByLabel("Name").fill("Morgan Promoter");
  await card.getByLabel("Email").fill(`morgan-${suffix}@example.test`);
  await card.getByRole("button", { name: "Save buyer" }).click();
  await expect(card.getByText("Buyer: Morgan Promoter")).toBeVisible();

  await page.goto("/booking-campaigns");
  await page.getByLabel("Campaign name").fill(`Austin outreach ${suffix}`);
  await page.getByRole("button", { name: "Create campaign" }).click();
  await page.getByLabel(`Prospect for Austin outreach ${suffix}`).selectOption({ label: `${prospectName} · Austin` });
  await page.getByLabel(`Add recipient to Austin outreach ${suffix}`).click();
  await expect(page.getByText("ready")).toBeVisible();
  await page.getByLabel(`Preview campaign Austin outreach ${suffix}`).click();
  await expect(page.getByText("Personalized draft preview")).toBeVisible();
  await expect(page.getByText(`morgan-${suffix}@example.test`, { exact: true })).toBeVisible();
});

test("booking advisor produces reviewable, non-automated guidance", async ({ page }) => {
  await signInForBrowserTest(page);

  await page.goto("/advisor");
  const generate = page.getByRole("button", { name: "Generate booking brief" });
  if (await generate.isVisible().catch(() => false)) await generate.click();
  await expect(page.getByRole("heading", { name: "Current booking brief" })).toBeVisible();
  await expect(page.getByText(/never sends or changes records/i)).toBeVisible();
  await page.getByRole("button", { name: "Helpful", exact: true }).click();
});

test("novice manager intake produces grounded work and band operations records", async ({ page }) => {
  const suffix = Date.now().toString(36);
  await signInForBrowserTest(page);
  await page.goto("/manager");
  const intake = page.getByRole("heading", { name: "Tell StoryBoard enough to manage the tradeoffs" });
  if (await intake.isVisible().catch(() => false)) {
    await page.getByLabel("What kind of band?").selectOption("hybrid");
    await page.getByLabel("Career stage").fill("Local working band");
    await page.getByLabel("Home market").fill("Chicago, IL");
    await page.getByLabel("Genres").fill("rock, soul");
    await page.getByLabel("What would a great next 12 months look like?").fill("Release an EP and book six profitable regional shows.");
    await page.getByLabel("Band member names").fill("Alex\nMorgan");
    await page.getByLabel("Constraints").fill("Weeknight work schedules");
    await page.getByRole("button", { name: "Build my 90-day operating plan" }).click();
  }
  await expect(page.getByText("Today", { exact: true })).toBeVisible();
  await expect(page.getByTestId("manager-priority-explanation")).toContainText("Ranked first because");
  const cadenceCard = page.getByTestId("manager-cadence");
  await expect(cadenceCard.getByText("On request only", { exact: true })).toBeVisible();
  const providerPolicy = cadenceCard.getByTestId("manager-provider-context-policy");
  await expect(providerPolicy.getByText("Provider context: disabled", { exact: true })).toBeVisible();
  await expect(providerPolicy.getByText(/No Manager snapshot is sent to the model.*Restricted memory never leaves StoryBoard/)).toBeVisible();
  await cadenceCard.getByLabel("Prepare Manager briefs on schedule").check();
  await cadenceCard.getByLabel("Manager schedule timezone").fill("America/Chicago");
  await cadenceCard.getByLabel("Manager schedule hour").selectOption("9");
  await cadenceCard.getByLabel("Manager schedule audience").selectOption("owners");
  await cadenceCard.getByRole("button", { name: "Save cadence" }).click();
  await expect(cadenceCard.getByText("Manager cadence saved.", { exact: true })).toBeVisible();
  await expect(cadenceCard.getByText(/Mondays after 9:00 AM in America\/Chicago/)).toBeVisible();
  const planCard = page.getByRole("heading", { name: "90-day plan" }).locator("xpath=ancestor::div[contains(@class,'shadow-')][1]");
  await expect(planCard).toBeVisible();
  await expect(page.getByText(/\d+\/100 · At risk/i)).toBeVisible();
  await expect(planCard.getByText("Grow dependable show revenue", { exact: true })).toHaveCount(1);
  await expect(planCard.getByText("Complete the next release cycle", { exact: true })).toHaveCount(1);
  const liveGoalCard = planCard.getByText("Grow dependable show revenue", { exact: true }).locator("xpath=ancestor::div[contains(@class,'rounded-lg') and contains(@class,'border')][1]");
  await expect(liveGoalCard.getByLabel("Progress source")).toHaveValue("qualified_prospects");
  const liveGoalMeasurement = liveGoalCard.getByLabel("Progress source").locator("xpath=ancestor::div[@data-testid][1]");
  await expect(liveGoalMeasurement.getByText(/StoryBoard can verify 1/i)).toBeVisible();
  await liveGoalMeasurement.getByRole("button", { name: "Reconcile to 1" }).click();
  await expect(liveGoalMeasurement.getByText(/Recorded progress matches 1 current qualified or converted prospect/i)).toBeVisible();
  await expect(page.getByText("Finish the booking profile and define what a good-fit show means", { exact: true }).first()).toBeVisible();
  const context = page.getByTestId("manager-context");
  await expect(context.getByText(/45\/100 · Thin/i)).toBeVisible();
  await context.getByRole("button", { name: "Edit context" }).click();
  const alexContext = context.getByLabel("Responsibilities for Alex").locator("xpath=ancestor::div[contains(@class,'grid')][1]");
  await context.getByLabel("Responsibilities for Alex").fill("bandleader, booking");
  await context.getByLabel("Instruments for Alex").fill("vocals, guitar");
  const alexSaved = page.waitForResponse((response) => response.request().method() === "PATCH" && response.url().includes("/manager/members/") && response.ok());
  const alexContextRefreshed = page.waitForResponse((response) => response.request().method() === "GET" && response.url().includes("/manager/context-health") && response.ok());
  await alexContext.getByRole("button", { name: "Save" }).click();
  await Promise.all([alexSaved, alexContextRefreshed]);
  await expect(context.getByLabel("Responsibilities for Alex")).toHaveValue("bandleader, booking");
  await expect(context.getByLabel("Instruments for Alex")).toHaveValue("vocals, guitar");
  const morganContext = context.getByLabel("Responsibilities for Morgan").locator("xpath=ancestor::div[contains(@class,'grid')][1]");
  await context.getByLabel("Responsibilities for Morgan").fill("production, finances");
  await context.getByLabel("Instruments for Morgan").fill("drums");
  const morganSaved = page.waitForResponse((response) => response.request().method() === "PATCH" && response.url().includes("/manager/members/") && response.ok());
  const morganContextRefreshed = page.waitForResponse((response) => response.request().method() === "GET" && response.url().includes("/manager/context-health") && response.ok());
  await morganContext.getByRole("button", { name: "Save" }).click();
  await Promise.all([morganSaved, morganContextRefreshed]);
  await expect(context.getByLabel("Responsibilities for Morgan")).toHaveValue("production, finances");
  await expect(context.getByLabel("Instruments for Morgan")).toHaveValue("drums");
  await context.getByLabel("Availability expectations").fill("Respond to holds within 48 hours and protect two weekends each month.");
  await context.getByLabel("Current revenue sources (one per line)").fill("Private events\nTicketed shows");
  await context.getByLabel("Usable assets (one per line)").fill("Finished EP masters\nLive performance video");
  await context.getByRole("spinbutton").fill("500");
  await context.getByLabel("Business or payment name").fill("E2E Band LLC");
  const profileSaved = page.waitForResponse((response) => response.request().method() === "PUT" && response.url().includes("/manager/profile") && response.ok());
  const profileContextRefreshed = page.waitForResponse((response) => response.request().method() === "GET" && response.url().includes("/manager/context-health") && response.ok());
  await context.getByRole("button", { name: "Save operating profile" }).click();
  await Promise.all([profileSaved, profileContextRefreshed]);
  await expect(context.getByText(/82\/100 · Strong/i)).toBeVisible();
  await page.getByRole("button", { name: "Fill missing steps" }).click();
  await expect(planCard.getByText("Grow dependable show revenue", { exact: true })).toHaveCount(1);
  const newConversation = page.getByRole("button", { name: "New", exact: true });
  if (await newConversation.isVisible().catch(() => false)) await newConversation.click();
  const managerMessage = page.getByPlaceholder("Ask about priorities, shows, booking, money, or the band...");
  const evidenceCard = page.getByTestId("manager-evidence-health");
  await expect(evidenceCard.getByRole("heading", { name: "What the Manager can trust right now" })).toBeVisible();
  await expect(evidenceCard).toContainText("Deals and money");
  await expect(evidenceCard).toContainText("Missing");
  await managerMessage.fill("How sure are you, and what records are missing?");
  await page.getByRole("button", { name: "Send message" }).click();
  const evidenceReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: "operating coverage" }).last();
  await expect(evidenceReply).toContainText(/not a rating of the band/i);
  await expect(evidenceReply).toContainText(/Check these first:/i);
  const conversationHistory = page.getByLabel("Manager conversation history");
  await expect(conversationHistory).toBeVisible();
  const firstConversationId = await conversationHistory.inputValue();
  await page.getByRole("button", { name: "New", exact: true }).click();
  await expect(conversationHistory).toHaveValue("__new__");
  await managerMessage.fill("What needs my attention today?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(conversationHistory).not.toHaveValue("__new__");
  const secondConversationId = await conversationHistory.inputValue();
  expect(secondConversationId).not.toBe(firstConversationId);
  const conversationMessages = page.getByTestId("manager-conversation-messages");
  await conversationHistory.selectOption(firstConversationId);
  await expect(conversationMessages.getByText("How sure are you, and what records are missing?", { exact: true })).toBeVisible();
  await expect(conversationMessages.getByText("What needs my attention today?", { exact: true })).toHaveCount(0);
  await conversationHistory.selectOption(secondConversationId);
  await expect(conversationMessages.getByText("What needs my attention today?", { exact: true })).toBeVisible();
  await expect(conversationMessages.getByText("How sure are you, and what records are missing?", { exact: true })).toHaveCount(0);
  const checkIns = page.getByTestId("manager-capacity-check-ins");
  await expect(checkIns.getByRole("heading", { name: "Who has room for work right now?" })).toBeVisible();
  await checkIns.getByLabel("Capacity for Alex").selectOption("available");
  const alexCheckInSaved = page.waitForResponse((response) => response.request().method() === "POST" && response.url().includes("/manager/members/") && response.url().endsWith("/check-ins") && response.ok());
  await checkIns.getByRole("button", { name: "Save check-in" }).first().click();
  await alexCheckInSaved;
  await expect(page.getByText("Alex's capacity check-in was saved.", { exact: true })).toBeVisible();
  await checkIns.getByLabel("Capacity for Morgan").selectOption("limited");
  const morganCheckInSaved = page.waitForResponse((response) => response.request().method() === "POST" && response.url().includes("/manager/members/") && response.url().endsWith("/check-ins") && response.ok());
  await checkIns.getByRole("button", { name: "Save check-in" }).nth(1).click();
  await morganCheckInSaved;
  await expect(page.getByText("Morgan's capacity check-in was saved.", { exact: true })).toBeVisible();
  const teamLoad = page.getByTestId("manager-team-load");
  await expect(teamLoad.getByRole("heading", { name: "Team workload" })).toBeVisible();
  await expect(teamLoad).toContainText(/recorded tasks plus voluntary capacity check-ins/i);
  await expect(teamLoad).toContainText(/available/i);
  await managerMessage.fill("Who should own the unassigned work?");
  await page.getByRole("button", { name: "Send message" }).click();
  const assignmentProposal = page.getByText("Suggested task owner", { exact: true }).last().locator("xpath=ancestor::div[contains(@class,'rounded-xl')][1]");
  await expect(assignmentProposal).toContainText(/role match/i);
  await expect(page.locator("p.whitespace-pre-wrap").filter({ hasText: /current voluntary check-ins/i }).last()).toBeVisible();
  await managerMessage.fill("Why that?");
  await page.getByRole("button", { name: "Send message" }).click();
  const continuityReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: "I recommended" }).last();
  await expect(continuityReply).toContainText(/role match/i);
  await expect(page.getByText("Suggested task owner", { exact: true })).toHaveCount(1);
  await assignmentProposal.getByRole("button", { name: "Assign task" }).click();
  await expect(assignmentProposal.getByText("completed", { exact: true })).toBeVisible();
  const coachingPrompts = page.getByTestId("manager-coaching-prompts");
  await expect(coachingPrompts.getByRole("button", { name: "How does a show settlement work?" })).toBeVisible();
  await coachingPrompts.getByRole("button", { name: "How does a show settlement work?" }).click();
  await expect(managerMessage).toHaveValue("How does a show settlement work?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.locator("p.whitespace-pre-wrap").filter({ hasText: "A settlement is the post-show money check" })).toContainText(/In StoryBoard:/);
  await managerMessage.fill("What do you still need to know about our band?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.locator("p.whitespace-pre-wrap").filter({ hasText: "Context coverage is 82/100" })).toContainText(/not the band's quality or potential/i);
  await managerMessage.fill("Explain our next priority in plain language.");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.getByText("Explain our next priority in plain language.", { exact: true })).toBeVisible();
  const plainLanguageReply = conversationMessages
    .getByText("Explain our next priority in plain language.", { exact: true })
    .locator("xpath=ancestor::div[contains(@class,'rounded-2xl')][1]/following-sibling::div[1]");
  await expect(plainLanguageReply).toBeVisible();
  await plainLanguageReply.getByRole("button", { name: "Helpful", exact: true }).click();
  await expect(plainLanguageReply.getByText("Saved", { exact: true })).toBeVisible();
  await plainLanguageReply.getByRole("button", { name: "Add answer to evals", exact: true }).click();
  await expect(plainLanguageReply.getByText("answer in eval set", { exact: true })).toBeVisible();
  const responseReview = page.getByTestId("manager-response-review");
  await expect(responseReview.getByText("Review a recent Manager answer", { exact: true })).toBeVisible();
  await expect(responseReview).toContainText(/unrated/);
  const reviewedQuestion = await responseReview.getByText(/You asked:/).textContent();
  const reviewSaved = page.waitForResponse((response) => response.request().method() === "POST" && response.url().includes("/manager/messages/") && response.url().endsWith("/feedback") && response.ok());
  await responseReview.getByRole("button", { name: "Helpful", exact: true }).click();
  await reviewSaved;
  await expect(responseReview.getByText(/You asked:/)).not.toHaveText(reviewedQuestion ?? "");
  const responseEvalReview = page.getByTestId("manager-response-eval-review");
  await expect(responseEvalReview.getByText("Add reviewed answers to release checks", { exact: true })).toBeVisible();
  await expect(responseEvalReview).toContainText(reviewedQuestion ?? "You asked:");
  const evalPromoted = page.waitForResponse((response) => response.request().method() === "POST" && response.url().includes("/manager/messages/") && response.url().endsWith("/promote-eval") && response.ok());
  await responseEvalReview.getByRole("button", { name: "Add helpful answer to evals" }).click();
  await evalPromoted;
  await expect(responseEvalReview).toContainText("No rated answers are waiting for evaluation review.");
  const notUseful = page.getByRole("button", { name: "Not useful" });
  if (await notUseful.isVisible().catch(() => false)) {
    await notUseful.click();
    await expect(page.getByText("dismissed", { exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Add to eval set" }).click();
    await expect(page.getByText("in eval set", { exact: true })).toBeVisible();
  }
  await managerMessage.fill("Where does our money stand?");
  await expect(page.getByRole("button", { name: "Send message" })).toBeEnabled();
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.getByText("Where does our money stand?", { exact: true })).toBeVisible();
  const moneyReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: /books currently show/i }).last().locator("xpath=ancestor::div[contains(@class,'rounded-2xl')][1]");
  await expect(moneyReply).toBeVisible();
  await moneyReply.getByRole("button", { name: "Needs work", exact: true }).click();
  await moneyReply.getByLabel("What should improve?").selectOption("too_vague");
  await moneyReply.getByLabel("Correction (optional)").fill("Lead with the current balance and one next step.");
  await moneyReply.getByRole("button", { name: "Save feedback" }).click();
  await expect(moneyReply.getByText("Saved", { exact: true })).toBeVisible();
  await managerMessage.fill("Are we on track with the 90-day plan?");
  await page.getByRole("button", { name: "Send message" }).click();
  const planReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: "plan-health score is" });
  await expect(planReply).toBeVisible();
  await expect(planReply).toContainText(/real owner/i);
  const releaseGoalCard = planCard.getByText("Complete the next release cycle", { exact: true }).locator("xpath=ancestor::div[contains(@class,'rounded-lg') and contains(@class,'border')][1]");
  const targetDirection = releaseGoalCard.getByLabel("Target means");
  await targetDirection.selectOption("at_most");
  await expect(page.getByText("Goal target meaning updated. Manager advice now uses this direction everywhere.", { exact: true })).toBeVisible();
  await expect(page.getByText(/final result is not known before the deadline/i).first()).toBeVisible();
  await managerMessage.fill("Are we on track with Complete the next release cycle?");
  await page.getByRole("button", { name: "Send message" }).click();
  const targetReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: "not elapsed-time pace or probability" }).last();
  await expect(targetReply).toContainText(/final result is not known before the deadline/i);
  await managerMessage.fill("Remember that Morgan handles production advances");
  await page.getByRole("button", { name: "Send message" }).click();
  const memoryProposal = page.getByText("Suggested band memory", { exact: true }).last().locator("xpath=ancestor::div[contains(@class,'rounded-xl')][1]");
  await expect(memoryProposal.getByTestId("manager-memory-preview")).toHaveText("Morgan handles production advances");
  await memoryProposal.getByRole("button", { name: "Remember this" }).click();
  await expect(memoryProposal.getByText("completed", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText(/plan-health score is/i).last()).toBeVisible();
  await expect(page.getByRole("heading", { name: "What your manager remembers" })).toBeVisible();
  await expect(page.getByText("Morgan handles production advances", { exact: true }).last()).toBeVisible();
  await expect(page.getByTestId("manager-knowledge-health")).toContainText(/healthy/i);
  await expect(page.getByText("Profile source", { exact: true }).first()).toBeVisible();
  const correctAmbition = page.getByRole("button", { name: "Correct Twelve month ambition" });
  if (await correctAmbition.isVisible().catch(() => false)) {
    const correctedAmbition = `Release an EP before the regional run ${suffix}`;
    await correctAmbition.click();
    await page.getByLabel("Correct Twelve month ambition").fill(correctedAmbition);
    await page.getByRole("button", { name: "Save Twelve month ambition" }).click();
    await expect(page.getByText(correctedAmbition, { exact: true })).toBeVisible();
  }
  const updateProgress = page.getByRole("button", { name: "Update progress" }).first();
  if (await updateProgress.isVisible().catch(() => false)) {
    await updateProgress.click();
    await page.getByLabel("Current value").fill("1");
    await page.getByLabel("What changed? (optional)").fill(`E2E progress ${suffix}`);
    await page.getByRole("button", { name: "Record", exact: true }).click();
    await expect(page.getByText(/plan-health score|active goal|needs attention|on track/i).first()).toBeVisible();
  }
  const runChecks = page.getByRole("button", { name: "Run checks" });
  if (await runChecks.isVisible().catch(() => false)) {
    await runChecks.click();
    await expect(page.getByText("manager_os_v22", { exact: true })).toBeVisible();
    await expect(page.getByText("passed", { exact: true })).toBeVisible();
  }

  const decisionTitle = `Choose E2E market ${suffix}`;
  await managerMessage.fill("Should we book Milwaukee or Detroit?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.getByText("Suggested open decision", { exact: true })).toBeVisible();
  await expect(page.getByText(/tradeoffs are still unknown/i)).toBeVisible();
  await page.getByRole("button", { name: "Add decision draft" }).click();
  const draftCard = page.getByRole("heading", { name: "Should we book Milwaukee or Detroit" }).locator("xpath=ancestor::div[contains(@class,'rounded-xl')][1]");
  await expect(draftCard.getByText("needs framing", { exact: true })).toBeVisible();
  await draftCard.getByLabel("Decision framing title").fill(decisionTitle);
  await draftCard.getByLabel("Decision framing context").fill("The band has one open travel weekend.");
  await draftCard.getByLabel("Framing option 1", { exact: true }).fill("Milwaukee");
  await draftCard.getByLabel("Framing option 1 tradeoff").fill("Lower travel cost and a smaller venue list.");
  await draftCard.getByLabel("Framing option 2", { exact: true }).fill("Detroit");
  await draftCard.getByLabel("Framing option 2 tradeoff").fill("Higher travel cost and a stronger genre fit.");
  await draftCard.getByRole("button", { name: "Save framing" }).click();
  const decisionCard = page.getByRole("heading", { name: decisionTitle }).locator("xpath=ancestor::div[contains(@class,'rounded-xl')][1]");
  await expect(decisionCard).toBeVisible();
  await decisionCard.getByRole("radio", { name: /Milwaukee/ }).check();
  await decisionCard.getByLabel("Why this choice?").fill("It fits the lineup's work schedules.");
  await decisionCard.getByLabel("What result do you expect?").fill("Draw 75 people and earn a return invitation.");
  await decisionCard.getByLabel("Check the result on").fill("2026-07-01");
  await decisionCard.getByRole("button", { name: "Record the choice" }).click();
  await expect(decisionCard.getByText("review due", { exact: true })).toBeVisible();
  await decisionCard.getByRole("button", { name: "Review the result" }).click();
  await decisionCard.getByLabel("What was the result?").selectOption("mixed");
  await decisionCard.getByLabel("What actually happened, and what should the band carry forward?").fill("Attendance reached 80, but the return invitation is still unknown.");
  await decisionCard.getByRole("button", { name: "Save the lesson" }).click();
  await expect(page.getByText("Recently reviewed", { exact: true })).toBeVisible();
  await expect(page.getByText("Attendance reached 80, but the return invitation is still unknown.", { exact: false })).toBeVisible();
  await managerMessage.fill("What did we learn from that decision?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.locator("p.whitespace-pre-wrap").filter({ hasText: "recorded result is mixed" })).toContainText("Attendance reached 80");

  await page.goto("/tasks");
  const downstreamTaskTitle = "Choose one target market and qualify real prospects";
  const prerequisiteTaskTitle = "Finish the booking profile and define what a good-fit show means";
  await page.getByLabel(`Prerequisite for ${downstreamTaskTitle}`).selectOption({ label: prerequisiteTaskTitle });
  const downstreamTaskRow = page.getByLabel(`Prerequisite for ${downstreamTaskTitle}`).locator("xpath=ancestor::tr");
  await downstreamTaskRow.getByRole("button", { name: "Add" }).click();
  await expect(page.getByRole("button", { name: `Remove prerequisite ${prerequisiteTaskTitle} from ${downstreamTaskTitle}` })).toBeVisible();
  const firstPlanOwner = page.getByLabel("Owner for Finish the booking profile and define what a good-fit show means");
  const firstPlanTaskRow = firstPlanOwner.locator("xpath=ancestor::tr");
  await firstPlanOwner.selectOption({ label: "Alex" });
  await firstPlanTaskRow.getByLabel("Status for Finish the booking profile and define what a good-fit show means").selectOption("blocked");
  await firstPlanTaskRow.getByLabel("Waiting on for Finish the booking profile and define what a good-fit show means").fill("Bandleader");
  await firstPlanTaskRow.getByLabel("Blocker for Finish the booking profile and define what a good-fit show means").fill("The band has not agreed on the target room size.");
  const deferredDate = new Date(Date.now() + 10 * 86400000).toISOString().slice(0, 10);
  await firstPlanTaskRow.getByLabel("Due date for Finish the booking profile and define what a good-fit show means").fill(deferredDate);
  await firstPlanTaskRow.getByRole("button", { name: "Save" }).click();
  await expect(page.getByLabel("Owner for Finish the booking profile and define what a good-fit show means").locator("option:checked")).toHaveText("Alex");
  await expect(page.getByRole("heading", { name: "Blocked", exact: true })).toBeVisible();
  await expect(page.getByLabel("Blocker for Finish the booking profile and define what a good-fit show means")).toHaveValue("The band has not agreed on the target room size.");

  await page.goto("/manager");
  const goalPath = page.getByTestId("manager-goal-path");
  await expect(goalPath.getByRole("heading", { name: "Goals connected to real work" })).toBeVisible();
  await expect(goalPath).toContainText(/linked goal task|ready prerequisite|next:/i);
  const workSequence = page.getByTestId("manager-work-sequence");
  await expect(workSequence.getByRole("heading", { name: "What can move now" })).toBeVisible();
  await expect(workSequence).toContainText(downstreamTaskTitle);
  await expect(workSequence).toContainText(/waiting for.*Finish the booking profile/i);
  const followThrough = page.getByTestId("manager-commitments");
  await expect(followThrough.getByText(/open commitment.*intervention now/i)).toBeVisible();
  await expect(followThrough.getByText("The band has not agreed on the target room size.", { exact: false }).first()).toBeVisible();
  const blockedQuestion = page.getByPlaceholder("Ask about priorities, shows, booking, money, or the band...");
  await blockedQuestion.fill("What is blocked or slipping?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.locator("p.whitespace-pre-wrap").filter({ hasText: "target room size" })).toContainText("Bandleader");
  await blockedQuestion.fill("What can we do now, and what is waiting on another task?");
  await page.getByRole("button", { name: "Send message" }).click();
  const sequenceReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: "Ready now:" }).last();
  await expect(sequenceReply).toContainText("Waiting:");
  await expect(sequenceReply).toContainText(downstreamTaskTitle);
  await blockedQuestion.fill("What is the next move for our goal?");
  await page.getByRole("button", { name: "Send message" }).click();
  const goalPathReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: /goal path|active goal path/i }).last();
  await expect(goalPathReply).toContainText(/does not estimate effort, conversion, duration, or private capacity/i);

  await page.goto("/operations");
  await page.getByLabel("Title").fill(`E2E rehearsal ${suffix}`);
  const eventStart = new Date(Date.now() + 90 * 86400000);
  const localEventStart = new Date(eventStart.getTime() - eventStart.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  await page.getByLabel("Starts").fill(localEventStart);
  await page.getByRole("button", { name: "Add event" }).click();
  await expect(page.getByText(`E2E rehearsal ${suffix}`, { exact: true })).toBeVisible();
  await expect(page.getByText(/not show-ready yet/i)).toBeVisible();
  await expect(page.getByText(/confidence/i).first()).toBeVisible();
  await page.getByRole("button", { name: "Generate advance checklist" }).click();
  await expect(page.getByRole("button", { name: "Generate advance checklist" })).toHaveCount(0);
  await page.getByText("Manage readiness details", { exact: true }).click();
  await page.getByLabel(`Availability for Alex at E2E rehearsal ${suffix}`).selectOption("available");
  await expect(page.getByLabel(`Availability for Alex at E2E rehearsal ${suffix}`)).toHaveValue("available");
  await page.getByLabel(`Availability for Morgan at E2E rehearsal ${suffix}`).selectOption("available");
  await page.getByLabel(`Location name for E2E rehearsal ${suffix}`).fill("E2E Working Room");
  const localTime = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  await page.getByLabel(`Load-in for E2E rehearsal ${suffix}`).fill(localTime(new Date(eventStart.getTime() - 3 * 3600000)));
  await page.getByLabel(`Soundcheck for E2E rehearsal ${suffix}`).fill(localTime(new Date(eventStart.getTime() - 2 * 3600000)));
  await page.getByLabel(`Doors for E2E rehearsal ${suffix}`).fill(localTime(new Date(eventStart.getTime() - 1 * 3600000)));
  await page.getByLabel(`Set time for E2E rehearsal ${suffix}`).fill(localEventStart);
  await page.getByLabel(`Curfew for E2E rehearsal ${suffix}`).fill(localTime(new Date(eventStart.getTime() + 2 * 3600000)));
  await page.getByLabel(`Guarantee for E2E rehearsal ${suffix}`).fill("500");
  await page.getByLabel(`Deposit for E2E rehearsal ${suffix}`).fill("100");
  await page.getByLabel(`Production notes for E2E rehearsal ${suffix}`).fill("House PA, four vocal microphones, and shared backline.");
  await page.getByRole("button", { name: "Save event details" }).click();
  await expect(page.getByText(/E2E Working Room/)).toBeVisible();
  await expect(page.getByText("Availability: 2/2 active members available", { exact: true })).toBeVisible();
  await expect(page.getByText("20/20", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Open day-of view" }).click();
  await expect(page.getByRole("heading", { name: "Run of show" })).toBeVisible();
  await expect(page.getByText(/Next checkpoint: Load-in/i)).toBeVisible();
  await page.getByRole("button", { name: "Add checkpoint" }).click();
  await page.getByLabel("Checkpoint title").fill(`Band meal ${suffix}`);
  await page.getByLabel("Location (optional)").fill("Green room");
  await page.getByLabel("Checkpoint starts").fill(localTime(new Date(eventStart.getTime() - 2.5 * 3600000)));
  await page.getByLabel("Checkpoint ends (optional)").fill(localTime(new Date(eventStart.getTime() - 2.25 * 3600000)));
  await page.getByLabel("Checkpoint notes (optional)").fill("Confirm dietary order with the venue.");
  await page.getByRole("button", { name: "Save checkpoint" }).click();
  const checkpointEditor = page.getByTestId("run-of-show-editor");
  await expect(checkpointEditor.getByText(`Band meal ${suffix}`, { exact: true })).toBeVisible();
  await checkpointEditor.getByRole("button", { name: `Edit Band meal ${suffix}` }).click();
  await checkpointEditor.getByLabel(`Location for Band meal ${suffix}`).fill("Artist lounge");
  await checkpointEditor.getByRole("button", { name: "Save changes" }).click();
  await expect(checkpointEditor.getByText(/Artist lounge/)).toBeVisible();
  await page.reload();
  await expect(page.getByTestId("run-of-show-editor").getByText(`Band meal ${suffix}`, { exact: true })).toBeVisible();
  await expect(page.getByTestId("run-of-show-editor").getByText(/Artist lounge/)).toBeVisible();
  await expect(page.getByRole("heading", { name: "Lineup and assignments" })).toBeVisible();
  await expect(page.getByText("4 open · 0 overdue", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Done" }).first().click();
  await expect(page.getByText("3 open · 0 overdue", { exact: true })).toBeVisible();

  await page.goto("/manager");
  const showQuestion = page.getByPlaceholder("Ask about priorities, shows, booking, money, or the band...");
  await showQuestion.fill("Are we ready for our next show?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.locator("p.whitespace-pre-wrap").filter({ hasText: `E2E rehearsal ${suffix}` })).toContainText(/\d+\/100/);

  await page.goto("/operations");
  await page.getByRole("tab", { name: "Music & setlists" }).click();
  await page.getByPlaceholder("Song title").fill(`E2E song ${suffix}`);
  await page.getByRole("button", { name: "Add", exact: true }).click();
  await expect(page.getByText(`E2E song ${suffix}`)).toBeVisible();
  await page.getByRole("tab", { name: "Projects" }).click();
  await page.getByPlaceholder("Project name").fill(`E2E release ${suffix}`);
  const projectDue = new Date(Date.now() + 120 * 86400000).toISOString().slice(0, 10);
  await page.getByLabel("Project due date").fill(projectDue);
  await page.getByRole("button", { name: "Create project" }).click();
  await expect(page.getByText(`E2E release ${suffix}`, { exact: true })).toBeVisible();
  await page.goto("/manager");
  await page.getByRole("button", { name: "Refresh", exact: true }).click();
  await expect(page.getByRole("button", { name: "Build milestone plan" })).toBeVisible();
  await page.getByRole("button", { name: "Build milestone plan" }).click();
  await expect(page.getByText("Milestone plan created.", { exact: true })).toBeVisible();
  await page.goto("/operations");
  await page.getByRole("tab", { name: "Projects" }).click();
  const openProject = page.getByRole("link", { name: "Open project" });
  await openProject.evaluate((element) => element.scrollIntoView({ block: "center" }));
  await openProject.click();
  await expect(page.getByRole("heading", { name: "Milestone plan", exact: true })).toBeVisible();
  await expect(page.getByText(/0\/6 milestones complete/)).toBeVisible();
  const firstReleaseMilestone = "Lock the release goal, audience, and story";
  await page.getByLabel(`Owner for project milestone ${firstReleaseMilestone}`).selectOption({ label: "Alex" });
  await page.getByLabel(`Status for project milestone ${firstReleaseMilestone}`).selectOption("done");
  await expect(page.getByText(/1\/6 milestones complete/)).toBeVisible();
  await page.getByLabel("Project budget").fill("750");
  await page.getByLabel("Project success metrics").fill("100 first-week saves\n25 mailing-list signups");
  await page.getByLabel("Project description").fill("Release the finished EP with a focused regional campaign.");
  await page.getByRole("button", { name: "Save project facts" }).click();
  await page.getByLabel("Asset label").fill("Working folder");
  await page.getByLabel("Asset URL").fill("https://example.test/e2e-release");
  await page.getByRole("button", { name: "Add asset" }).click();
  await expect(page.getByRole("link", { name: "Working folder" })).toBeVisible();

  await page.goto("/manager");
  const releaseQuestion = page.getByPlaceholder("Ask about priorities, shows, booking, money, or the band...");
  await releaseQuestion.fill("How is our release project going?");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.locator("p.whitespace-pre-wrap").filter({ hasText: `E2E release ${suffix}` })).toContainText(/\d+\/100/);

  await page.goto("/operations");
  await page.getByRole("tab", { name: "Deals" }).click();
  await page.getByPlaceholder("Show or deal").fill(`E2E offer ${suffix}`);
  await page.getByPlaceholder("Buyer name").fill("E2E Buyer");
  await page.getByPlaceholder("Buyer email").fill(`buyer-${suffix}@example.test`);
  await page.getByPlaceholder("Offer amount (USD)").fill("500");
  await page.getByRole("button", { name: "Record offer" }).click();
  await expect(page.getByText(`E2E offer ${suffix}`, { exact: true }).first()).toBeVisible();

  const currentDeal = page.getByText(`E2E offer ${suffix}`, { exact: true }).first().locator("..").locator("..").locator("..");
  const generateAgreement = currentDeal.getByRole("button", { name: "Generate agreement PDF" });
  if (await generateAgreement.isDisabled()) {
    await page.getByPlaceholder("Template name").fill(`E2E agreement ${suffix}`);
    await page.getByRole("button", { name: "Create reviewed version" }).click();
    await page.getByRole("button", { name: "Activate" }).last().click();
  }
  await generateAgreement.click();
  await expect(currentDeal.getByText(/agreement v1/i)).toBeVisible();

  const invoiceForm = page.getByLabel("Invoice deal").locator("..");
  await page.getByLabel("Invoice deal").selectOption({ label: `E2E offer ${suffix}` });
  await invoiceForm.getByPlaceholder("Invoice number").fill(`E2E-${suffix}`);
  await invoiceForm.getByPlaceholder("Recipient").fill("E2E Buyer");
  await invoiceForm.getByPlaceholder("Amount (USD)").fill("500");
  await invoiceForm.getByRole("button", { name: "Create invoice" }).click();
  await page.getByPlaceholder("Payment").last().fill("100");
  await page.getByRole("button", { name: "Record", exact: true }).last().click();
  await expect(page.getByText("Balance USD 400.00")).toBeVisible();

  const expenseForm = page.getByLabel("Expense event or project").locator("..");
  await page.getByLabel("Expense event or project").selectOption({ label: `E2E rehearsal ${suffix}` });
  await expenseForm.getByPlaceholder("Expense description").fill("Fuel");
  await expenseForm.getByPlaceholder("Amount (USD)").fill("25");
  await expenseForm.getByRole("button", { name: "Record expense" }).click();
  await expect(page.getByText(/^Fuel/).first()).toBeVisible();
  await page.getByLabel("Settlement event").selectOption({ label: `E2E rehearsal ${suffix}` });
  await page.getByPlaceholder("Gross USD").fill("500");
  await page.getByRole("button", { name: "Calculate" }).click();
  await page.getByRole("button", { name: "Finalize PDF" }).last().click();
  await expect(page.getByText("finalized", { exact: true }).last()).toBeVisible();

  await page.getByRole("tab", { name: "Events" }).click();
  const completedShow = page.locator("article").filter({ hasText: `E2E rehearsal ${suffix}` });
  await completedShow.getByText("Manage readiness details", { exact: true }).click();
  const completedSetAt = new Date(Date.now() - 2 * 3600000);
  await page.getByLabel(`Event start for E2E rehearsal ${suffix}`).fill(localTime(completedSetAt));
  await page.getByLabel(`Load-in for E2E rehearsal ${suffix}`).fill(localTime(new Date(completedSetAt.getTime() - 3 * 3600000)));
  await page.getByLabel(`Soundcheck for E2E rehearsal ${suffix}`).fill(localTime(new Date(completedSetAt.getTime() - 2 * 3600000)));
  await page.getByLabel(`Doors for E2E rehearsal ${suffix}`).fill(localTime(new Date(completedSetAt.getTime() - 3600000)));
  await page.getByLabel(`Set time for E2E rehearsal ${suffix}`).fill(localTime(completedSetAt));
  await page.getByLabel(`Curfew for E2E rehearsal ${suffix}`).fill(localTime(new Date(completedSetAt.getTime() + 3600000)));
  await page.getByLabel(`Status for E2E rehearsal ${suffix}`).selectOption("completed");
  await page.getByLabel(`Attendance for E2E rehearsal ${suffix}`).fill("135");
  await page.getByLabel(`Gross revenue for E2E rehearsal ${suffix}`).fill("500");
  await page.getByLabel(`Post-show notes for E2E rehearsal ${suffix}`).fill("Strong audience response; tighten the changeover next time.");
  await page.getByLabel(`Relationship outcome for E2E rehearsal ${suffix}`).fill("Buyer invited a return pitch.");
  await completedShow.getByRole("button", { name: "Save event details" }).click();
  await expect(completedShow.locator("span").filter({ hasText: /^completed$/ })).toBeVisible();

  await page.goto("/manager");
  const outcomes = page.getByTestId("manager-outcome-review");
  await expect(outcomes.getByRole("heading", { name: "Recent outcomes" })).toBeVisible();
  await expect(outcomes.getByText("135", { exact: true })).toBeVisible();
  await expect(outcomes.getByText(/Finalized net \$475\.00/)).toBeVisible();
  const outcomeQuestion = page.getByPlaceholder("Ask about priorities, shows, booking, money, or the band...");
  await outcomeQuestion.fill(`What is the balance on Invoice E2E-${suffix}?`);
  await page.getByRole("button", { name: "Send message" }).click();
  const invoiceReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: `Invoice E2E-${suffix} is` }).last();
  await expect(invoiceReply).toContainText(/remaining balance is USD 400\.00/);
  await expect(invoiceReply).not.toContainText(/An invoice is a request for payment/);
  await outcomeQuestion.fill("What did we learn from our recent shows?");
  await page.getByRole("button", { name: "Send message" }).click();
  const outcomeReply = page.locator("p.whitespace-pre-wrap").filter({ hasText: "Recorded attendance totals 135" });
  await expect(outcomeReply).toContainText(/finalized net USD 475\.00/);
});
