import { PageHeader } from "@storyboard/ui";
import { serverApiFetch } from "@/lib/api-server";
import type { BandMember, ManagerCommitmentHealth, ManagerContextHealth, ManagerConversation, ManagerDecision, ManagerEvalExample, ManagerEvaluationRun, ManagerGoal, ManagerKnowledgeHealth, ManagerLearningSummary, ManagerMemoryFact, ManagerOutcomeReview, ManagerPlanHealth, ManagerProfile, ManagerProviderContextPolicy, ManagerResponseEvalExample, ManagerRun, ManagerSettings } from "@/lib/types";
import { ManagerClient } from "./manager-client";

export default async function ManagerPage() {
  let profile: ManagerProfile | null = null; let members: BandMember[] = []; let goals: ManagerGoal[] = []; let decisions: ManagerDecision[] = []; let brief: ManagerRun | null = null; let memory: ManagerMemoryFact[] = []; let learning: ManagerLearningSummary | null = null; let planHealth: ManagerPlanHealth | null = null; let contextHealth: ManagerContextHealth | null = null; let knowledgeHealth: ManagerKnowledgeHealth | null = null; let commitmentHealth: ManagerCommitmentHealth | null = null; let outcomeReview: ManagerOutcomeReview | null = null; let conversation: ManagerConversation | null = null; let evalExamples: ManagerEvalExample[] | null = null; let responseEvalExamples: ManagerResponseEvalExample[] | null = null; let latestEvaluation: ManagerEvaluationRun | null = null; let settings: ManagerSettings | null = null; let providerContextPolicy: ManagerProviderContextPolicy | null = null; let isOwner = false;
  try { [profile, members, goals, decisions, brief, memory, learning, planHealth, contextHealth, knowledgeHealth, commitmentHealth, outcomeReview] = await Promise.all([serverApiFetch<ManagerProfile | null>("/manager/profile", { cache: "no-store" }), serverApiFetch<BandMember[]>("/manager/members", { cache: "no-store" }), serverApiFetch<ManagerGoal[]>("/manager/goals", { cache: "no-store" }), serverApiFetch<ManagerDecision[]>("/manager/decisions", { cache: "no-store" }), serverApiFetch<ManagerRun | null>("/manager/brief?cadence=daily", { cache: "no-store" }), serverApiFetch<ManagerMemoryFact[]>("/manager/memory", { cache: "no-store" }), serverApiFetch<ManagerLearningSummary>("/manager/learning", { cache: "no-store" }), serverApiFetch<ManagerPlanHealth>("/manager/plan-health", { cache: "no-store" }), serverApiFetch<ManagerContextHealth>("/manager/context-health", { cache: "no-store" }), serverApiFetch<ManagerKnowledgeHealth>("/manager/knowledge-health", { cache: "no-store" }), serverApiFetch<ManagerCommitmentHealth>("/manager/commitment-health", { cache: "no-store" }), serverApiFetch<ManagerOutcomeReview>("/manager/outcome-review?days=90", { cache: "no-store" })]); } catch { /* setup remains usable */ }
  try { const recent = await serverApiFetch<ManagerConversation[]>("/manager/conversations?limit=1", { cache: "no-store" }); if (recent[0]) conversation = await serverApiFetch<ManagerConversation>(`/manager/conversations/${recent[0].id}`, { cache: "no-store" }); } catch { /* a new conversation can still start */ }
  try { settings = await serverApiFetch<ManagerSettings>("/manager/settings", { cache: "no-store" }); } catch { /* cadence controls can stay unavailable */ }
  try { const me = await serverApiFetch<{ currentArtistId: string | null; memberships: { artistId: string; role: string }[] }>("/auth/me", { cache: "no-store" }); const artistId = me.currentArtistId ?? me.memberships[0]?.artistId; isOwner = me.memberships.some((membership) => membership.artistId === artistId && membership.role === "owner"); } catch { /* server guard still enforces owner-only writes */ }
  try { [evalExamples, responseEvalExamples, latestEvaluation] = await Promise.all([serverApiFetch<ManagerEvalExample[]>("/manager/eval-examples", { cache: "no-store" }), serverApiFetch<ManagerResponseEvalExample[]>("/manager/response-eval-examples", { cache: "no-store" }), serverApiFetch<ManagerEvaluationRun | null>("/manager/evaluations/latest", { cache: "no-store" })]); } catch { /* non-owners do not manage evaluations */ }
  try { providerContextPolicy = await serverApiFetch<ManagerProviderContextPolicy>("/manager/provider-context-policy", { cache: "no-store" }); } catch { /* non-owners do not manage provider policy */ }
  return <div className="space-y-8"><PageHeader title="Manager" description="Your priorities, decisions, risks, and next actions — grounded in StoryBoard records and gated before outside action." /><ManagerClient initialProfile={profile} initialMembers={members} initialGoals={goals} initialDecisions={decisions} initialBrief={brief} initialConversation={conversation} initialMemory={memory} initialLearning={learning} initialPlanHealth={planHealth} initialContextHealth={contextHealth} initialKnowledgeHealth={knowledgeHealth} initialCommitmentHealth={commitmentHealth} initialOutcomeReview={outcomeReview} initialEvalExamples={evalExamples} initialResponseEvalExamples={responseEvalExamples} initialEvaluation={latestEvaluation} initialSettings={settings} initialProviderContextPolicy={providerContextPolicy} isOwner={isOwner} /></div>;
}
