import { PageHeader } from "@storyboard/ui";
import { serverApiFetch } from "@/lib/api-server";
import type { BandMember, ManagerContextHealth, ManagerConversation, ManagerDecision, ManagerEvalExample, ManagerEvaluationRun, ManagerGoal, ManagerLearningSummary, ManagerMemoryFact, ManagerOutcomeReview, ManagerPlanHealth, ManagerProfile, ManagerRun } from "@/lib/types";
import { ManagerClient } from "./manager-client";

export default async function ManagerPage() {
  let profile: ManagerProfile | null = null; let members: BandMember[] = []; let goals: ManagerGoal[] = []; let decisions: ManagerDecision[] = []; let brief: ManagerRun | null = null; let memory: ManagerMemoryFact[] = []; let learning: ManagerLearningSummary | null = null; let planHealth: ManagerPlanHealth | null = null; let contextHealth: ManagerContextHealth | null = null; let outcomeReview: ManagerOutcomeReview | null = null; let conversation: ManagerConversation | null = null; let evalExamples: ManagerEvalExample[] | null = null; let latestEvaluation: ManagerEvaluationRun | null = null;
  try { [profile, members, goals, decisions, brief, memory, learning, planHealth, contextHealth, outcomeReview] = await Promise.all([serverApiFetch<ManagerProfile | null>("/manager/profile", { cache: "no-store" }), serverApiFetch<BandMember[]>("/manager/members", { cache: "no-store" }), serverApiFetch<ManagerGoal[]>("/manager/goals", { cache: "no-store" }), serverApiFetch<ManagerDecision[]>("/manager/decisions", { cache: "no-store" }), serverApiFetch<ManagerRun | null>("/manager/brief?cadence=daily", { cache: "no-store" }), serverApiFetch<ManagerMemoryFact[]>("/manager/memory", { cache: "no-store" }), serverApiFetch<ManagerLearningSummary>("/manager/learning", { cache: "no-store" }), serverApiFetch<ManagerPlanHealth>("/manager/plan-health", { cache: "no-store" }), serverApiFetch<ManagerContextHealth>("/manager/context-health", { cache: "no-store" }), serverApiFetch<ManagerOutcomeReview>("/manager/outcome-review?days=90", { cache: "no-store" })]); } catch { /* setup remains usable */ }
  try { const recent = await serverApiFetch<ManagerConversation[]>("/manager/conversations?limit=1", { cache: "no-store" }); if (recent[0]) conversation = await serverApiFetch<ManagerConversation>(`/manager/conversations/${recent[0].id}`, { cache: "no-store" }); } catch { /* a new conversation can still start */ }
  try { [evalExamples, latestEvaluation] = await Promise.all([serverApiFetch<ManagerEvalExample[]>("/manager/eval-examples", { cache: "no-store" }), serverApiFetch<ManagerEvaluationRun | null>("/manager/evaluations/latest", { cache: "no-store" })]); } catch { /* non-owners do not manage evaluations */ }
  return <div className="space-y-8"><PageHeader title="Manager" description="Your priorities, decisions, risks, and next actions — grounded in StoryBoard records and gated before outside action." /><ManagerClient initialProfile={profile} initialMembers={members} initialGoals={goals} initialDecisions={decisions} initialBrief={brief} initialConversation={conversation} initialMemory={memory} initialLearning={learning} initialPlanHealth={planHealth} initialContextHealth={contextHealth} initialOutcomeReview={outcomeReview} initialEvalExamples={evalExamples} initialEvaluation={latestEvaluation} /></div>;
}
