import { BadRequestException, Body, Controller, Get, Headers, Param, Patch, Post, Put, Query, Req, UseGuards } from "@nestjs/common";
import type { FastifyRequest } from "fastify";
import { z } from "zod";
import { bandMemberCreateSchema, bandMemberPatchSchema, managerChatSchema, managerDecisionCreateSchema, managerGoalCreateSchema, managerGoalPatchSchema, managerInitiativeCreateSchema, managerInitiativePatchSchema, managerProfileSchema, managerSettingsSchema } from "@storyboard/shared";
import { CurrentOperator } from "../auth/current-operator.decorator";
import { MembershipService } from "../auth/membership.service";
import { RolePolicyService } from "../auth/role-policy.service";
import type { RequestOperator } from "../auth/request-operator";
import { SessionAuthGuard } from "../auth/session-auth.guard";
import { ManagerService } from "./manager.service";

const intakeSchema = z.object({ profile: managerProfileSchema, members: z.array(bandMemberCreateSchema).max(30).default([]) }).strict();

@Controller("manager")
@UseGuards(SessionAuthGuard)
export class ManagerController {
  constructor(private readonly manager: ManagerService, private readonly membership: MembershipService, private readonly roles: RolePolicyService) {}
  private artistId(operatorId: string, req: FastifyRequest, header?: string) { return this.membership.resolveArtistId(operatorId, req.storyboardSession ?? null, header); }
  private parse<T>(schema: z.ZodType<T>, body: unknown): T { const parsed = schema.safeParse(body ?? {}); if (!parsed.success) throw new BadRequestException(parsed.error.flatten()); return parsed.data; }
  @Get("profile") async profile(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.profile(await this.artistId(op.id, req, h)); }
  @Put("profile") async putProfile(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.putProfile(artistId, this.parse(managerProfileSchema, body), op.email, op.id); }
  @Get("members") async members(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.members(await this.artistId(op.id, req, h)); }
  @Post("members") async createMember(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createMember(artistId, this.parse(bandMemberCreateSchema, body), op.email, op.id); }
  @Patch("members/:id") async patchMember(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.patchMember(artistId, id, this.parse(bandMemberPatchSchema, body), op.email, op.id); }
  @Get("goals") async goals(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.goals(await this.artistId(op.id, req, h)); }
  @Post("goals") async createGoal(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createGoal(artistId, this.parse(managerGoalCreateSchema, body), op.email, op.id); }
  @Patch("goals/:id") async patchGoal(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.patchGoal(artistId, id, this.parse(managerGoalPatchSchema, body), op.email, op.id); }
  @Get("initiatives") async initiatives(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.initiatives(await this.artistId(op.id, req, h)); }
  @Post("initiatives") async createInitiative(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createInitiative(artistId, this.parse(managerInitiativeCreateSchema, body), op.email, op.id); }
  @Patch("initiatives/:id") async patchInitiative(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.patchInitiative(artistId, id, this.parse(managerInitiativePatchSchema, body), op.email, op.id); }
  @Get("decisions") async decisions(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.decisions(await this.artistId(op.id, req, h)); }
  @Post("decisions") async decision(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createDecision(artistId, this.parse(managerDecisionCreateSchema, body), op.email, op.id); }
  @Post("intake/complete") async intake(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.completeIntake(artistId, this.parse(intakeSchema, body), op.email, op.id); }
  @Get("brief") async brief(@Query("cadence") cadence: string | undefined, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); const c = cadence === "weekly" ? "weekly" : "daily"; return this.manager.currentBrief(artistId, c, op.email, op.id); }
  @Post("brief/generate") async generate(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); const cadence = z.object({ cadence: z.enum(["daily","weekly"]).default("daily") }).strict().parse(body ?? {}).cadence; return this.manager.generateBrief(artistId, cadence, op.email, op.id); }
  @Post("chat") async chat(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.chat(artistId, this.parse(managerChatSchema, body), op.email, op.id); }
  @Post("recommendations/:id/accept") recommendationAccept(@Param("id") id: string, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.recommendation(id, "accepted", op, req, h); }
  @Post("recommendations/:id/dismiss") recommendationDismiss(@Param("id") id: string, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.recommendation(id, "dismissed", op, req, h); }
  @Post("recommendations/:id/complete") recommendationComplete(@Param("id") id: string, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.recommendation(id, "completed", op, req, h); }
  private async recommendation(id: string, outcome: "accepted"|"dismissed"|"completed", op: RequestOperator, req: FastifyRequest, h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.recommendation(artistId, id, outcome, op.email, op.id); }
  @Get("settings") async settings(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.settings(await this.artistId(op.id, req, h)); }
  @Put("settings") async putSettings(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.updateSettings(artistId, this.parse(managerSettingsSchema, body), op.email, op.id); }
}
