import { BadRequestException, Body, Controller, Get, Headers, Param, Patch, Post, Put, Query, Req, UseGuards } from "@nestjs/common";
import type { FastifyRequest } from "fastify";
import { z } from "zod";
import { bandMemberCheckInCreateSchema, bandMemberCreateSchema, bandMemberPatchSchema, managerChatSchema, managerDecisionCreateSchema, managerDecisionPatchSchema, managerDecisionReviewSchema, managerEvalPromotionSchema, managerEvaluationRunSchema, managerGoalCreateSchema, managerGoalPatchSchema, managerGoalProgressSchema, managerGoalProgressSyncSchema, managerInitiativeCreateSchema, managerInitiativePatchSchema, managerMemoryPatchSchema, managerMessageFeedbackSchema, managerProfileSchema, managerRecommendationFeedbackSchema, managerResponseEvalPromotionSchema, managerResponseEvalResolutionSchema, managerSettingsSchema } from "@storyboard/shared";
import { CurrentOperator } from "../auth/current-operator.decorator";
import { MembershipService } from "../auth/membership.service";
import { RolePolicyService } from "../auth/role-policy.service";
import type { RequestOperator } from "../auth/request-operator";
import { SessionAuthGuard } from "../auth/session-auth.guard";
import { ArtistMembershipRole } from "../generated/prisma/enums";
import { ManagerService } from "./manager.service";

const intakeSchema = z.object({ profile: managerProfileSchema, members: z.array(bandMemberCreateSchema).max(30).default([]) }).strict();

@Controller("manager")
@UseGuards(SessionAuthGuard)
export class ManagerController {
  constructor(private readonly manager: ManagerService, private readonly membership: MembershipService, private readonly roles: RolePolicyService) {}
  private artistId(operatorId: string, req: FastifyRequest, header?: string) { return this.membership.resolveArtistId(operatorId, req.storyboardSession ?? null, header); }
  private parse<T>(schema: z.ZodType<T>, body: unknown): T { const parsed = schema.safeParse(body ?? {}); if (!parsed.success) throw new BadRequestException(parsed.error.flatten()); return parsed.data; }
  @Get("profile") async profile(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.profile(await this.artistId(op.id, req, h)); }
  @Put("profile") async putProfile(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.putProfile(artistId, this.parse(managerProfileSchema, body), op.email, op.id); }
  @Get("members") async members(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.members(await this.artistId(op.id, req, h)); }
  @Post("members") async createMember(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createMember(artistId, this.parse(bandMemberCreateSchema, body), op.email, op.id); }
  @Patch("members/:id") async patchMember(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.patchMember(artistId, id, this.parse(bandMemberPatchSchema, body), op.email, op.id); }
  @Get("member-check-ins") async memberCheckIns(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.memberCheckIns(await this.artistId(op.id, req, h)); }
  @Post("members/:id/check-ins") async recordMemberCheckIn(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.recordMemberCheckIn(artistId, id, this.parse(bandMemberCheckInCreateSchema, body), op.email, op.id); }
  @Get("goals") async goals(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.goals(await this.artistId(op.id, req, h)); }
  @Post("goals") async createGoal(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createGoal(artistId, this.parse(managerGoalCreateSchema, body), op.email, op.id); }
  @Patch("goals/:id") async patchGoal(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.patchGoal(artistId, id, this.parse(managerGoalPatchSchema, body), op.email, op.id); }
  @Get("goals/:id/progress") async goalProgress(@Param("id") id: string, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.goalProgress(await this.artistId(op.id, req, h), id); }
  @Post("goals/:id/progress") async recordGoalProgress(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.recordGoalProgress(artistId, id, this.parse(managerGoalProgressSchema, body), op.email, op.id); }
  @Get("goal-measurements") async goalMeasurements(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.goalMeasurements(await this.artistId(op.id, req, h)); }
  @Post("goals/:id/sync-progress") async syncGoalProgress(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.syncGoalProgress(artistId, id, this.parse(managerGoalProgressSyncSchema, body), op.email, op.id); }
  @Get("initiatives") async initiatives(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.initiatives(await this.artistId(op.id, req, h)); }
  @Post("initiatives") async createInitiative(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createInitiative(artistId, this.parse(managerInitiativeCreateSchema, body), op.email, op.id); }
  @Patch("initiatives/:id") async patchInitiative(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.patchInitiative(artistId, id, this.parse(managerInitiativePatchSchema, body), op.email, op.id); }
  @Get("decisions") async decisions(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.decisions(await this.artistId(op.id, req, h)); }
  @Post("decisions") async decision(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.createDecision(artistId, this.parse(managerDecisionCreateSchema, body), op.email, op.id); }
  @Patch("decisions/:id") async patchDecision(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.patchDecision(artistId, id, this.parse(managerDecisionPatchSchema, body), op.email, op.id); }
  @Post("decisions/:id/review") async reviewDecision(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.reviewDecision(artistId, id, this.parse(managerDecisionReviewSchema, body), op.email, op.id); }
  @Post("intake/complete") async intake(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.completeIntake(artistId, this.parse(intakeSchema, body), op.email, op.id); }
  @Get("plan") async plan(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.plan(await this.artistId(op.id, req, h)); }
  @Post("plan/ensure") async ensurePlan(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.ensurePlan(artistId, op.email, op.id); }
  @Get("brief") async brief(@Query("cadence") cadence: string | undefined, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); const c = cadence === "weekly" ? "weekly" : "daily"; return this.manager.currentBrief(artistId, c, op.email, op.id); }
  @Post("brief/generate") async generate(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); const cadence = z.object({ cadence: z.enum(["daily","weekly"]).default("daily") }).strict().parse(body ?? {}).cadence; return this.manager.generateBrief(artistId, cadence, op.email, op.id); }
  @Get("memory") async memory(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); const role = await this.roles.getRole(op.id, artistId); return this.manager.memory(artistId, role === ArtistMembershipRole.owner); }
  @Patch("memory/:id") async patchMemory(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); const input = this.parse(managerMemoryPatchSchema, body); const role = await this.roles.getRole(op.id, artistId); if (input.sensitivity) await this.roles.assertOwner(op.id, artistId); return this.manager.patchMemory(artistId, id, input, role === ArtistMembershipRole.owner, op.email, op.id); }
  @Get("learning") async learning(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.learningSummary(await this.artistId(op.id, req, h)); }
  @Get("recommendation-eval-review") async recommendationEvalReview(@Query("limit") limit: string | undefined, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); const parsed = z.coerce.number().int().min(1).max(5).default(3).safeParse(limit); if (!parsed.success) throw new BadRequestException("Invalid recommendation evaluation review limit"); return this.manager.recommendationEvalReview(artistId, parsed.data); }
  @Get("response-review") async responseReview(@Query("limit") limit: string | undefined, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); const parsed = z.coerce.number().int().min(1).max(5).default(3).safeParse(limit); if (!parsed.success) throw new BadRequestException("Invalid response review limit"); return this.manager.responseReview(artistId, op.id, parsed.data); }
  @Get("response-eval-review") async responseEvalReview(@Query("limit") limit: string | undefined, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); const parsed = z.coerce.number().int().min(1).max(5).default(3).safeParse(limit); if (!parsed.success) throw new BadRequestException("Invalid response evaluation review limit"); return this.manager.responseEvalReview(artistId, op.id, parsed.data); }
  @Get("context-health") async contextHealth(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.contextHealth(await this.artistId(op.id, req, h)); }
  @Get("knowledge-health") async knowledgeHealth(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); const role = await this.roles.getRole(op.id, artistId); return this.manager.knowledgeHealth(artistId, role === ArtistMembershipRole.owner); }
  @Get("evidence-health") async evidenceHealth(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.evidenceHealth(await this.artistId(op.id, req, h)); }
  @Get("goal-paths") async goalPaths(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.goalPaths(await this.artistId(op.id, req, h)); }
  @Get("work-sequence") async workSequence(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.workSequence(await this.artistId(op.id, req, h)); }
  @Get("commitment-health") async commitmentHealth(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.commitmentHealth(await this.artistId(op.id, req, h)); }
  @Get("team-load") async teamLoad(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.teamLoad(await this.artistId(op.id, req, h)); }
  @Get("outcome-review") async outcomeReview(@Query("days") days: string | undefined, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const parsed = z.coerce.number().int().min(7).max(365).default(90).safeParse(days); if (!parsed.success) throw new BadRequestException("Outcome review days must be between 7 and 365"); return this.manager.outcomeReview(await this.artistId(op.id, req, h), parsed.data); }
  @Get("plan-health") async planHealth(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.planHealth(await this.artistId(op.id, req, h)); }
  @Get("eval-examples") async evalExamples(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.evalExamples(artistId); }
  @Get("response-eval-examples") async responseEvalExamples(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.responseEvalExamples(artistId); }
  @Post("response-eval-examples/:id/resolve") async resolveResponseEval(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.resolveResponseEvalExample(artistId, id, this.parse(managerResponseEvalResolutionSchema, body), op.email, op.id); }
  @Get("evaluations/latest") async latestEvaluation(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.latestEvaluation(artistId); }
  @Post("evaluations/run") async runEvaluation(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); const input = this.parse(managerEvaluationRunSchema, body); return this.manager.runEvaluation(artistId, input.candidateVersion, op.email, op.id); }
  @Get("conversations") async conversations(@Query("limit") limit: string | undefined, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); const parsed = z.coerce.number().int().min(1).max(20).default(10).safeParse(limit); if (!parsed.success) throw new BadRequestException("Invalid conversation limit"); return this.manager.conversations(artistId, parsed.data); }
  @Get("conversations/:id") async conversation(@Param("id") id: string, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.conversation(await this.artistId(op.id, req, h), id, op.id); }
  @Post("chat") async chat(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.chat(artistId, this.parse(managerChatSchema, body), op.email, op.id); }
  @Post("messages/:id/feedback") async messageFeedback(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.messageFeedback(artistId, id, this.parse(managerMessageFeedbackSchema, body), op.email, op.id); }
  @Post("messages/:id/promote-eval") async promoteResponseEval(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.promoteResponseEvalExample(artistId, id, this.parse(managerResponseEvalPromotionSchema, body), op.email, op.id); }
  @Post("recommendations/:id/accept") recommendationAccept(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.recommendation(id, "accepted", body, op, req, h); }
  @Post("recommendations/:id/dismiss") recommendationDismiss(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.recommendation(id, "dismissed", body, op, req, h); }
  @Post("recommendations/:id/complete") recommendationComplete(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.recommendation(id, "completed", body, op, req, h); }
  @Post("recommendations/:id/promote-eval") async promoteEval(@Param("id") id: string, @Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.promoteEvalExample(artistId, id, this.parse(managerEvalPromotionSchema, body), op.email, op.id); }
  private async recommendation(id: string, outcome: "accepted"|"dismissed"|"completed", body: unknown, op: RequestOperator, req: FastifyRequest, h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertCanMutateWorkflow(op.id, artistId); return this.manager.recommendation(artistId, id, outcome, this.parse(managerRecommendationFeedbackSchema, body), op.email, op.id); }
  @Get("settings") async settings(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { return this.manager.settings(await this.artistId(op.id, req, h)); }
  @Get("provider-context-policy") async providerContextPolicy(@CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.providerContextPolicy(artistId); }
  @Put("settings") async putSettings(@Body() body: unknown, @CurrentOperator() op: RequestOperator, @Req() req: FastifyRequest, @Headers("x-artist-id") h?: string) { const artistId = await this.artistId(op.id, req, h); await this.roles.assertOwner(op.id, artistId); return this.manager.updateSettings(artistId, this.parse(managerSettingsSchema, body), op.email, op.id); }
}
