"use client";

import { Badge, EmptyState, SurfaceCard } from "@storyboard/ui";
import { CheckCircle2, MailSearch, RefreshCw, Sparkles } from "lucide-react";
import { useState } from "react";
import { apiFetch } from "@/lib/api";
import type { BookingReply, BookingReplySettings } from "@/lib/types";

export function BookingInboxClient({ initialReplies, initialSettings }: { initialReplies: BookingReply[]; initialSettings: BookingReplySettings }) {
  const [replies, setReplies] = useState(initialReplies); const [settings, setSettings] = useState(initialSettings); const [busy, setBusy] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  async function reload() { setReplies(await apiFetch<BookingReply[]>("/booking-replies")); setSettings(await apiFetch<BookingReplySettings>("/booking-replies/settings")); }
  async function sync() { setBusy("sync"); setNotice(null); try { const result = await apiFetch<{ created: number }>("/booking-replies/sync", { method: "POST" }); await reload(); setNotice(`${result.created} new repl${result.created === 1 ? "y" : "ies"} found.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Reply sync failed"); } finally { setBusy(null); } }
  async function updateSettings(patch: Partial<BookingReplySettings>) { setBusy("settings"); setNotice(null); try { setSettings(await apiFetch<BookingReplySettings>("/booking-replies/settings", { method: "PATCH", json: patch })); } catch (error) { setNotice(error instanceof Error ? error.message : "Settings update failed"); } finally { setBusy(null); } }
  async function action(id: string, path: string, json?: unknown) { setBusy(`${path}-${id}`); setNotice(null); try { await apiFetch(`/booking-replies/${id}/${path}`, { method: "POST", ...(json ? { json } : {}) }); await reload(); setNotice(path === "prepare-approval" ? "Reply draft is waiting in Approvals." : "Reply updated."); } catch (error) { setNotice(error instanceof Error ? error.message : "Action failed"); } finally { setBusy(null); } }
  return <div className="space-y-5">{notice ? <div role="status" className="rounded-xl border border-[var(--border)] bg-[var(--surface-1)] px-4 py-3 text-sm text-[var(--text-secondary)]">{notice}</div> : null}<SurfaceCard><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold text-[var(--text-primary)]">Tracked Gmail threads</h2><p className="mt-1 max-w-2xl text-sm text-[var(--text-muted)]">StoryBoard checks only campaign threads it created. It does not search or display your general inbox.</p></div><button type="button" className="sb-btn-primary" disabled={busy !== null || !settings.syncEnabled} onClick={() => void sync()}><RefreshCw className="h-4 w-4" />Check for replies</button></div><div className="mt-4 flex flex-wrap gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.syncEnabled} disabled={!settings.deploymentEnabled || !settings.scopeReady || busy !== null} onChange={(event) => void updateSettings({ syncEnabled: event.target.checked })} />Periodic reply checks</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.aiAnalysisEnabled} disabled={busy !== null} onChange={(event) => void updateSettings({ aiAnalysisEnabled: event.target.checked })} />Allow AI analysis of a selected reply</label></div>{!settings.deploymentEnabled ? <p className="mt-3 text-xs text-amber-300">Reply sync is disabled on this deployment. Manual campaign outcomes remain available.</p> : settings.reconnectRequired ? <p className="mt-3 text-xs text-amber-300">Reconnect Google as an owner to grant the new read-only Gmail permission.</p> : null}{settings.lastSyncedAt ? <p className="mt-3 text-xs text-[var(--text-muted)]">Last checked {new Date(settings.lastSyncedAt).toLocaleString()}{settings.lastSyncError ? ` · ${settings.lastSyncError}` : ""}</p> : null}</SurfaceCard>{replies.length === 0 ? <EmptyState title="No tracked replies yet" description="After an approved campaign draft is sent or StoryBoard sends an approved pitch, new replies will appear here." icon={<MailSearch className="h-6 w-6" />} /> : <div className="space-y-3">{replies.map((reply) => <ReplyCard key={reply.id} reply={reply} busy={busy} aiEnabled={settings.aiAnalysisEnabled} onAction={action} />)}</div>}</div>;
}

function ReplyCard({ reply, busy, aiEnabled, onAction }: { reply: BookingReply; busy: string | null; aiEnabled: boolean; onAction: (id: string, path: string, json?: unknown) => Promise<void> }) {
  const [subject, setSubject] = useState(reply.suggestedReplySubject ?? (reply.subject?.startsWith("Re:") ? reply.subject : `Re: ${reply.subject ?? reply.recipient.prospect.name}`)); const [body, setBody] = useState(reply.suggestedReplyBody ?? "");
  return <SurfaceCard><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-semibold text-[var(--text-primary)]">{reply.recipient.prospect.name}</h2><Badge variant={reply.processingStatus === "unread" ? "warning" : "neutral"}>{reply.intent ?? reply.processingStatus}</Badge></div><p className="mt-1 text-xs text-[var(--text-muted)]">{reply.fromName ?? reply.fromEmail} · {new Date(reply.receivedAt).toLocaleString()} · {reply.recipient.campaign.name}</p></div>{aiEnabled && !reply.analyzedAt ? <button className="sb-btn-secondary" disabled={busy !== null} onClick={() => void onAction(reply.id, "analyze")}><Sparkles className="h-4 w-4" />Analyze reply</button> : null}</div><p className="mt-4 rounded-lg bg-[var(--surface-0)] p-3 text-sm text-[var(--text-secondary)]">{reply.snippet ?? "Open the tracked thread in Gmail to read the complete message."}</p>{reply.summary ? <div className="mt-4 rounded-lg border border-[var(--border)] p-3"><p className="text-sm font-medium">AI summary</p><p className="mt-1 text-sm text-[var(--text-secondary)]">{reply.summary}</p><p className="mt-2 text-xs text-[var(--text-muted)]">Confidence {Math.round((reply.confidence ?? 0) * 100)}%{reply.proposedFeeMinor != null ? ` · proposed ${reply.proposedCurrency ?? ""} ${(reply.proposedFeeMinor / 100).toFixed(2)}` : ""}{reply.proposedDate ? ` · ${new Date(reply.proposedDate).toLocaleDateString()}` : ""}</p>{reply.recipient.opportunity && !reply.termsAppliedAt ? <button className="sb-btn-secondary mt-3" disabled={busy !== null} onClick={() => void onAction(reply.id, "apply-terms")}><CheckCircle2 className="h-4 w-4" />Apply reviewed terms</button> : null}</div> : null}<div className="mt-4 grid gap-2"><input aria-label="Reply subject" className="sb-input" value={subject} onChange={(event) => setSubject(event.target.value)} /><textarea aria-label="Reply body" className="sb-input min-h-28" value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write or paste the response you want Gmail to hold as a draft…" /><button className="sb-btn-primary w-fit" disabled={!body.trim() || busy !== null} onClick={() => void onAction(reply.id, "prepare-approval", { subject, body })}>Preview & request approval</button></div></SurfaceCard>;
}
