"use client";

import { Badge, SurfaceCard } from "@storyboard/ui";
import { ArrowLeft, CheckCircle2, Plus, RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { apiFetch } from "@/lib/api";
import type { BandMember, ProjectReadinessResponse } from "@/lib/types";

function dateInput(value?: string | null) { return value ? new Date(value).toISOString().slice(0, 10) : ""; }
function dollars(value?: number | null) { return value == null ? "" : (value / 100).toFixed(2); }
function money(value: number | null | undefined, currency: string) { return value == null ? "Not recorded" : `${currency} ${(value / 100).toFixed(2)}`; }

export function ProjectClient({ initialData, members }: { initialData: ProjectReadinessResponse; members: BandMember[] }) {
  const { project, readiness } = initialData;
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [status, setStatus] = useState(project.status);
  const [dueAt, setDueAt] = useState(dateInput(project.dueAt));
  const [description, setDescription] = useState(project.description ?? "");
  const [budget, setBudget] = useState(dollars(project.budgetMinor));
  const [metrics, setMetrics] = useState((project.successMetrics ?? []).join("\n"));
  const [assetLabel, setAssetLabel] = useState("");
  const [assetUrl, setAssetUrl] = useState("");
  const router = useRouter();
  async function mutate(key: string, path: string, json: unknown, method = "POST") { setBusy(key); setError(""); try { await apiFetch(path, { method, json }); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The update failed"); } finally { setBusy(null); } }
  const completion = readiness.totalMilestones ? Math.round(readiness.completedMilestones / readiness.totalMilestones * 100) : 0;
  return <div className="space-y-5 pb-12">
    <div className="flex flex-wrap items-center justify-between gap-3"><a className="sb-btn-ghost" href="/operations"><ArrowLeft className="h-4 w-4" /> Band operations</a><button className="sb-btn-secondary" type="button" onClick={() => router.refresh()}><RefreshCw className="h-4 w-4" /> Refresh</button></div>
    {error ? <p role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</p> : null}
    <SurfaceCard><div className="flex flex-wrap items-center gap-2"><Badge variant={readiness.status === "on_track" || readiness.status === "complete" ? "success" : readiness.status === "closed" ? "neutral" : readiness.status === "blocked" || readiness.status === "off_track" ? "danger" : "warning"}>{readiness.status.replaceAll("_", " ")}</Badge><span className="text-xl font-semibold">{readiness.score}/100</span><span className="text-xs text-[var(--text-muted)]">{Math.round(readiness.confidence * 100)}% record confidence</span></div><h2 className="mt-4 text-xl font-semibold">{readiness.headline}</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{readiness.nextAction}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-[var(--surface-2)]"><div className="h-full bg-[var(--accent)]" style={{ width: `${completion}%` }} /></div><p className="mt-1 text-xs text-[var(--text-muted)]">{readiness.completedMilestones}/{readiness.totalMilestones} milestones complete · {readiness.overdueMilestones} overdue · {readiness.blockedMilestones} blocked</p>{readiness.gaps[0] ? <p className="mt-3 text-xs text-[var(--text-muted)]">First gap: {readiness.gaps[0].detail}</p> : null}</SurfaceCard>

    <div className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><SurfaceCard><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Milestone plan</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Template generation fills missing source-keyed milestones and preserves edits.</p></div><button className="sb-btn-secondary" disabled={busy !== null || !project.dueAt} onClick={() => void mutate("generate", `/projects/${project.id}/generate-plan`, {})}>Generate missing milestones</button></div><div className="mt-4 space-y-2">{project.tasks?.map((task) => <div key={task.id} className="rounded-lg border border-[var(--border)] p-3"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className={task.status === "done" ? "text-sm text-[var(--text-muted)] line-through" : "text-sm font-medium"}>{task.title}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{task.dueAt ? `Due ${new Date(task.dueAt).toLocaleDateString()}` : "No date"}</p></div>{task.status === "done" ? <Badge variant="success">done</Badge> : null}</div><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_150px]"><select aria-label={`Owner for project milestone ${task.title}`} className="sb-select" value={task.bandMemberId ?? (task.ownerLabel ? `legacy:${task.ownerLabel}` : "")} disabled={busy !== null} onChange={(change) => void mutate(`owner-${task.id}`, `/tasks/${task.id}`, { bandMemberId: change.target.value && !change.target.value.startsWith("legacy:") ? change.target.value : null }, "PATCH")}><option value="">Unassigned</option>{task.ownerLabel && !task.bandMemberId ? <option value={`legacy:${task.ownerLabel}`}>{task.ownerLabel} (legacy label)</option> : null}{members.map((member) => <option key={member.id} value={member.id} disabled={!member.active}>{member.name}{member.active ? "" : " (inactive)"}</option>)}</select><select aria-label={`Status for project milestone ${task.title}`} className="sb-select" value={task.status} disabled={busy !== null} onChange={(change) => void mutate(`status-${task.id}`, `/tasks/${task.id}`, { status: change.target.value }, "PATCH")}>{["todo", "in_progress", "blocked", "done"].map((value) => <option key={value}>{value.replace("_", " ")}</option>)}</select></div></div>)}{!project.tasks?.length ? <p className="rounded-lg border border-dashed border-[var(--border)] p-4 text-sm text-[var(--text-muted)]">No milestones yet. Set a due date, then generate the appropriate starter sequence.</p> : null}</div></SurfaceCard>
      <div className="space-y-5"><SurfaceCard><h2 className="font-semibold">Project facts</h2><form className="mt-4 space-y-3" onSubmit={(submit) => { submit.preventDefault(); void mutate("project", `/projects/${project.id}`, { status, description: description || null, dueAt: dueAt ? new Date(`${dueAt}T12:00:00`).toISOString() : null, budgetMinor: budget === "" ? null : Math.round(Number(budget) * 100), successMetrics: metrics.split("\n").map((item) => item.trim()).filter(Boolean) }, "PATCH"); }}><label><span className="sb-label">Status</span><select aria-label="Project status" className="sb-select mt-1.5" value={status} onChange={(change) => setStatus(change.target.value)}>{["draft", "active", "paused", "completed", "cancelled"].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="sb-label">Target date</span><input aria-label="Project target date" className="sb-input mt-1.5" type="date" value={dueAt} onChange={(change) => setDueAt(change.target.value)} /></label><label><span className="sb-label">Working budget (USD)</span><input aria-label="Project budget" className="sb-input mt-1.5" type="number" min="0" step="0.01" value={budget} onChange={(change) => setBudget(change.target.value)} /></label><label><span className="sb-label">Description</span><textarea aria-label="Project description" className="sb-input mt-1.5 min-h-20" value={description} onChange={(change) => setDescription(change.target.value)} /></label><label><span className="sb-label">Success metrics (one per line)</span><textarea aria-label="Project success metrics" className="sb-input mt-1.5 min-h-24" value={metrics} onChange={(change) => setMetrics(change.target.value)} /></label><button className="sb-btn-primary" disabled={busy !== null}><CheckCircle2 className="h-4 w-4" /> Save project facts</button></form></SurfaceCard>
      <SurfaceCard><h2 className="font-semibold">Budget snapshot</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-[var(--text-muted)]">Budget</dt><dd>{money(project.budgetMinor, project.currency)}</dd></div><div><dt className="text-[var(--text-muted)]">Recorded spend</dt><dd>{money(readiness.spendMinor, project.currency)}</dd></div><div><dt className="text-[var(--text-muted)]">Remaining</dt><dd>{money(readiness.budgetRemainingMinor, project.currency)}</dd></div><div><dt className="text-[var(--text-muted)]">Linked events</dt><dd>{project.events?.length ?? 0}</dd></div></dl></SurfaceCard></div></div>

    <SurfaceCard><h2 className="font-semibold">Working assets</h2><div className="mt-4 flex flex-wrap gap-2">{project.assets?.map((asset) => <a key={`${asset.label}-${asset.url}`} className="sb-btn-secondary" href={asset.url} target="_blank" rel="noreferrer">{asset.label}</a>)}{!project.assets?.length ? <p className="text-sm text-[var(--text-muted)]">No assets attached.</p> : null}</div><form className="mt-4 grid gap-2 sm:grid-cols-[1fr_1.5fr_auto]" onSubmit={(submit) => { submit.preventDefault(); if (!assetLabel || !assetUrl) return; void mutate("asset", `/projects/${project.id}`, { assets: [...(project.assets ?? []), { label: assetLabel, url: assetUrl }] }, "PATCH"); setAssetLabel(""); setAssetUrl(""); }}><input aria-label="Asset label" className="sb-input" value={assetLabel} onChange={(change) => setAssetLabel(change.target.value)} placeholder="Master, artwork, brief…" /><input aria-label="Asset URL" className="sb-input" type="url" value={assetUrl} onChange={(change) => setAssetUrl(change.target.value)} placeholder="https://" /><button className="sb-btn-secondary" disabled={busy !== null || !assetLabel || !assetUrl}><Plus className="h-4 w-4" /> Add asset</button></form></SurfaceCard>
  </div>;
}
